/**
 * ANUVAAD KI KITAAB.
 *
 * Chaabi khud Hinglish wala shabd hai — jo app me pehle se likha tha. Isliye:
 *
 *   • Jis shabd ka anuvaad yahan nahi hai, wo Hinglish me hi dikhta hai.
 *     App tooti nahi, aadha-adhoora bhi padhne layak rehta hai.
 *   • Naya page banane wale ko koi key-list yaad nahi rakhni. `t('Naya bill')`
 *     likho, bas. Baad me `npm run check` bata dega ki kya kya bacha hai.
 *
 * Bhasha ke faisle jo jaan-boojh kar liye gaye hain:
 *
 *   • Hindi me bhi wahi shabd rakhe hain jo dukaan me bole jate hain —
 *     "बिल", "स्टॉक", "ऑर्डर", "पेमेंट"। Inka "shuddh" anuvaad (बीजक,
 *     भांडार) koi dukaandaar nahi bolta; wo padh kar ruk jayega.
 *   • Sarkari shabd — GST, GSTIN, HSN, CGST, SGST, IGST, UPI, CSV — jaise ke
 *     waise. Ye kagaz pe bhi English me hi chhapte hain.
 *   • Naam, misaal ka data (Ramesh Auto Parts, BRG-6203) aur brand yahan hain
 *     hi nahi — unka anuvaad hota hi nahi.
 */
const DICT = {
  '— limit paar ho gayi': { hi: '— हद पार हो गई', en: '— over the limit' },
  '(credit bacha hai)': { hi: '(जमा बचा है)', en: '(credit remaining)' },
  '₹ me. Khali chhodein to koi hadd nahi': { hi: '₹ में। खाली छोड़ें तो कोई हद नहीं', en: 'In ₹. Leave blank for no limit' },
  '0 = koi limit nahi': { hi: '0 = कोई सीमा नहीं', en: '0 = no limit' },
  '1. Sample file download karein': { hi: '1. सैंपल फाइल डाउनलोड करें', en: '1. Download the sample file' },
  '15 character. Pehle 2 digit aapke state ke honge.': { hi: '15 अक्षर। पहले 2 अंक आपके राज्य के होंगे।', en: '15 characters. First 2 digits are your state code.' },
  '2. Apni file upload karein': { hi: '2. अपनी फाइल अपलोड करें', en: '2. Upload your file' },
  '3. Check karein, phir import': { hi: '3. जाँच लें, फिर इम्पोर्ट', en: '3. Review, then import' },
  '30 din': { hi: '30 दिन', en: '30 days' },
  Aadha: { hi: 'आधा', en: 'Half' },
  Aaj: { hi: 'आज', en: 'Today' },
  'Aaj aaya': { hi: 'आज आया', en: 'Received today' },
  'Aaj ke order': { hi: 'आज के ऑर्डर', en: "Today's orders" },
  'Aaj ki sale': { hi: 'आज की सेल', en: "Today's sales" },
  'Aaj paisa aaya': { hi: 'आज पैसा आया', en: 'Money received today' },
  'Aaj ye dekh lijiye': { hi: 'आज ये देख लीजिए', en: 'Look at this today' },
  'Aakhri baar aaya': { hi: 'आखिरी बार आया', en: 'Last seen' },
  'Aapka account': { hi: 'आपका अकाउंट', en: 'Your account' },
  'Aapka naam': { hi: 'आपका नाम', en: 'Your name' },
  'Aapka saara data aapke apne MongoDB database me hai — hamare paas uski koi copy nahi. Iska matlab: database ka backup on rakhna aapki zimmedari hai.': { hi: 'आपका सारा डेटा आपके अपने MongoDB डेटाबेस में है — हमारे पास उसकी कोई कॉपी नहीं। मतलब: डेटाबेस का बैकअप चालू रखना आपकी ज़िम्मेदारी है।', en: 'All your data lives in your own MongoDB database — we keep no copy. That means keeping database backups on is your responsibility.' },
  'Aapka saara data ek file me — mahine me ek baar le lena achhi aadat hai': { hi: 'आपका सारा डेटा एक फाइल में — महीने में एक बार ले लेना अच्छी आदत है', en: 'All your data in one file — taking it once a month is a good habit' },
  'Aapka saara maal, stock aur rate': { hi: 'आपका सारा माल, स्टॉक और रेट', en: 'All your goods, stock and rates' },
  'Aapki dukaan ka naam': { hi: 'आपकी दुकान का नाम', en: 'Your shop name' },
  'Aapki UPI ID': { hi: 'आपकी UPI ID', en: 'Your UPI ID' },
  'Aapko kitne ka pada': { hi: 'आपको कितने का पड़ा', en: 'What it cost you' },
  'Abhi abhi kya hua': { hi: 'अभी अभी क्या हुआ', en: 'What just happened' },
  'Abhi app pe nahi aaya': { hi: 'अभी ऐप पर नहीं आया', en: 'Not on the app yet' },
  'Abhi ka stock': { hi: 'अभी का स्टॉक', en: 'Current stock' },
  'Abhi kitna diya': { hi: 'अभी कितना दिया', en: 'Paid now' },
  'Abhi kitna maal pada hai': { hi: 'अभी कितना माल पड़ा है', en: 'How much stock is lying' },
  'Abhi kitna mila': { hi: 'अभी कितना मिला', en: 'Received now' },
  'Abhi koi bill nahi': { hi: 'अभी कोई बिल नहीं', en: 'No bills yet' },
  'Abhi koi notification nahi': { hi: 'अभी कोई सूचना नहीं', en: 'No notifications yet' },
  'Abhi koi order nahi': { hi: 'अभी कोई ऑर्डर नहीं', en: 'No orders yet' },
  'Abhi koi payment nahi': { hi: 'अभी कोई पेमेंट नहीं', en: 'No payments yet' },
  'Abhi koi purchase nahi': { hi: 'अभी कोई खरीद नहीं', en: 'No purchases yet' },
  'Abhi koi record nahi': { hi: 'अभी कोई रिकॉर्ड नहीं', en: 'No records yet' },
  'Abhi koi return nahi': { hi: 'अभी कोई रिटर्न नहीं', en: 'No returns yet' },
  'Abhi stock': { hi: 'अभी स्टॉक', en: 'Stock now' },
  'Abhi tak koi movement nahi': { hi: 'अभी तक कोई हलचल नहीं', en: 'No movement yet' },
  'Account ban gaya!': { hi: 'अकाउंट बन गया!', en: 'Account created!' },
  'Account banayein': { hi: 'अकाउंट बनाएं', en: 'Create account' },
  Active: { hi: 'चालू', en: 'Active' },
  Add: { hi: 'जोड़ें', en: 'Add' },
  Address: { hi: 'पता', en: 'Address' },
  'Address aur GST': { hi: 'पता और GST', en: 'Address and GST' },
  'Address aur GST bhar lein — invoice pe yahi chhapega. Phir "Invite link" tab se apna link WhatsApp pe bhej dein.': { hi: 'पता और GST भर लें — बिल पर यही छपेगा। फिर "Invite link" टैब से अपना लिंक WhatsApp पर भेज दें।', en: 'Fill in address and GST — this is what prints on the invoice. Then send your link from the "Invite link" tab on WhatsApp.' },
  'Address line 1': { hi: 'पता लाइन 1', en: 'Address line 1' },
  'Address line 2': { hi: 'पता लाइन 2', en: 'Address line 2' },
  advance: { hi: 'एडवांस', en: 'advance' },
  'Agar iska koi order, bill ya payment hai to delete nahi hoga — sirf block ho jayega, taaki purane record kharab na hon.': { hi: 'अगर इसका कोई ऑर्डर, बिल या पेमेंट है तो डिलीट नहीं होगा — सिर्फ ब्लॉक होगा, ताकि पुराने रिकॉर्ड खराब न हों।', en: 'If this party has any order, bill or payment it will not be deleted — only blocked, so old records stay intact.' },
  'Agla page': { hi: 'अगला पेज', en: 'Next page' },
  'Akshar ka size': { hi: 'अक्षर का आकार', en: 'Text size' },
  'Alag alag CSV — CA ko dena ho ya khud dekhna ho': { hi: 'अलग अलग CSV — CA को देना हो या खुद देखना हो', en: 'Separate CSVs — to hand to your CA or to check yourself' },
  Amount: { hi: 'रकम', en: 'Amount' },
  'Amount in words': { hi: 'रकम शब्दों में', en: 'Amount in words' },
  'Apna account': { hi: 'अपना अकाउंट', en: 'My account' },
  'Apna login bana lijiye': { hi: 'अपना लॉगिन बना लीजिए', en: 'Create your login' },
  'Apna password': { hi: 'अपना पासवर्ड', en: 'Your password' },
  'Apne aap approve kar do': { hi: 'अपने आप अप्रूव कर दो', en: 'Approve automatically' },
  'Apne phone number se login karein': { hi: 'अपने फोन नंबर से लॉगिन करें', en: 'Log in with your phone number' },
  'Apni pehchaan ke liye, marzi ho to chhod dein': { hi: 'अपनी पहचान के लिए, मर्ज़ी हो तो छोड़ दें', en: 'For your own reference, optional' },
  'App ka account': { hi: 'ऐप का अकाउंट', en: 'App account' },
  'App ke shabd kis bhasha me dikhein': { hi: 'ऐप के शब्द किस भाषा में दिखें', en: 'Which language the app should use' },
  'Approval baaki': { hi: 'अप्रूवल बाकी', en: 'Approval pending' },
  Approve: { hi: 'अप्रूव करें', en: 'Approve' },
  'Aur item add karein': { hi: 'और आइटम जोड़ें', en: 'Add more items' },
  Baaki: { hi: 'बाकी', en: 'Due' },
  'Badal dein': { hi: 'बदल दें', en: 'Change' },
  'Badalne ke liye list me "Stock" button dabayein': { hi: 'बदलने के लिए लिस्ट में "Stock" बटन दबाएं', en: 'To change it, press the "Stock" button in the list' },
  'Badha (+)': { hi: 'बढ़ा (+)', en: 'Added (+)' },
  Band: { hi: 'बंद', en: 'Off' },
  'Band karein': { hi: 'बंद करें', en: 'Close' },
  'Band karein to poora paisa usi waqt lena hoga': { hi: 'बंद करें तो पूरा पैसा उसी वक्त लेना होगा', en: 'Turn this off and the full amount must be collected at once' },
  'Band karne par koi naya retailer register nahi kar payega': { hi: 'बंद करने पर कोई नया रिटेलर रजिस्टर नहीं कर पाएगा', en: 'When off, no new retailer can register' },
  Barcode: { hi: 'बारकोड', en: 'Barcode' },
  'Bearing sirf 6 hai, baaki agle hafte': { hi: 'बेयरिंग सिर्फ 6 है, बाकी अगले हफ्ते', en: 'Only 6 bearings left, rest next week' },
  'Bearings, Chains, Plugs — jaise apne maal ke hisaab se bana lein.': { hi: 'Bearings, Chains, Plugs — जैसे अपने माल के हिसाब से बना लें।', en: 'Bearings, Chains, Plugs — make them to suit your goods.' },
  'Bhar dein to sirf yahi number jud payega': { hi: 'भर दें तो सिर्फ यही नंबर जुड़ पाएगा', en: 'Fill this and only this number can join' },
  'Bharna zaroori nahi — par bhar denge to search me foran mil jayega': { hi: 'भरना ज़रूरी नहीं — पर भर देंगे तो सर्च में फौरन मिल जाएगा', en: 'Not required — but filling it makes search find it instantly' },
  Bhasha: { hi: 'भाषा', en: 'Language' },
  'Bheji hui link': { hi: 'भेजी हुई लिंक', en: 'Link sent' },
  Bill: { hi: 'बिल', en: 'Bill' },
  'Bill aisa dikhega: INV/26-27/0001': { hi: 'बिल ऐसा दिखेगा: INV/26-27/0001', en: 'The bill will look like: INV/26-27/0001' },
  'Bill aur stock ke chhote settings': { hi: 'बिल और स्टॉक की छोटी सेटिंग', en: 'Small bill and stock settings' },
  'Bill banate hi stock ghatega aur retailer ke khate me udhaar chadhega': { hi: 'बिल बनते ही स्टॉक घटेगा और रिटेलर के खाते में उधार चढ़ेगा', en: 'Making the bill reduces stock and adds credit to the retailer ledger' },
  'Bill banate hi stock ghatta hai aur khata banta hai': { hi: 'बिल बनते ही स्टॉक घटता है और खाता बनता है', en: 'Making a bill reduces stock and creates the ledger entry' },
  'Bill banayein': { hi: 'बिल बनाएं', en: 'Create bill' },
  'Bill banega ya paisa aayega tab yahan dikhega': { hi: 'बिल बनेगा या पैसा आएगा तब यहां दिखेगा', en: 'Shows up here when a bill is made or money comes in' },
  'Bill banega, paisa aayega ya koi setting badlegi — sab yahan likha jayega.': { hi: 'बिल बनेगा, पैसा आएगा या कोई सेटिंग बदलेगी — सब यहां लिखा जाएगा।', en: 'Bills, payments and setting changes — everything gets recorded here.' },
  'Bill chhapte waqt hamesha safed kagaz hi chhapega — chahe raat wala roop chalu ho.': { hi: 'बिल छापते वक्त हमेशा सफेद कागज ही छपेगा — चाहे रात वाला रूप चालू हो।', en: 'Printing always uses the light theme — even when dark mode is on.' },
  'Bill dekhein': { hi: 'बिल देखें', en: 'View bill' },
  'Bill delete nahi hoga — number record me rahega, par stock wapas aa jayega aur khata ulta ho jayega.': { hi: 'बिल डिलीट नहीं होगा — नंबर रिकॉर्ड में रहेगा, पर स्टॉक वापस आ जाएगा और खाता उल्टा हो जाएगा।', en: 'The bill is not deleted — the number stays on record, but stock returns and the ledger is reversed.' },
  'Bill isse bada nahi': { hi: 'बिल इससे बड़ा नहीं', en: 'Bill cannot exceed this' },
  'Bill number ya retailer...': { hi: 'बिल नंबर या रिटेलर...', en: 'Bill number or retailer...' },
  'Bill pe extra discount': { hi: 'बिल पर अतिरिक्त छूट', en: 'Extra discount on bill' },
  'Bill pe IGST lagega ya CGST+SGST — isse tay hoga': { hi: 'बिल पर IGST लगेगा या CGST+SGST — इससे तय होगा', en: 'Decides whether IGST or CGST+SGST applies on the bill' },
  'Bill to': { hi: 'बिल किसके नाम', en: 'Bill to' },
  Bills: { hi: 'बिल', en: 'Bills' },
  'Bina bill': { hi: 'बिना बिल', en: 'Without bill' },
  'Bina category': { hi: 'बिना श्रेणी', en: 'No category' },
  'Bina GST ke bhi poori app chalegi — items, orders, khata, payments sab kuch. Bas bill pe tax nahi lagega.': { hi: 'बिना GST के भी पूरी ऐप चलेगी — आइटम, ऑर्डर, खाता, पेमेंट सब कुछ। बस बिल पर टैक्स नहीं लगेगा।', en: 'The whole app works without GST too — items, orders, ledger, payments. Only tax will not apply on bills.' },
  Block: { hi: 'ब्लॉक करें', en: 'Block' },
  Cancel: { hi: 'रहने दें', en: 'Cancel' },
  'Cash, UPI, bank — paisa aane-jaane ka poora record': { hi: 'कैश, UPI, बैंक — पैसे के आने-जाने का पूरा रिकॉर्ड', en: 'Cash, UPI, bank — the full record of money in and out' },
  Categories: { hi: 'श्रेणियां', en: 'Categories' },
  Category: { hi: 'श्रेणी', en: 'Category' },
  'Chal rahe hain': { hi: 'चल रहे हैं', en: 'In progress' },
  Chhupayein: { hi: 'छुपाएं', en: 'Hide' },
  'Chune hue items ka khaas rate hat jayega — un par wapas wholesale price lagega.': { hi: 'चुने हुए आइटम का खास रेट हट जाएगा — उन पर वापस होलसेल प्राइस लगेगा।', en: 'The special rate on the selected items will be removed — wholesale price applies again.' },
  'Code / SKU': { hi: 'कोड / SKU', en: 'Code / SKU' },
  'Company / Brand': { hi: 'कंपनी / ब्रांड', en: 'Company / Brand' },
  'Company warranty, bill ke saath': { hi: 'कंपनी वारंटी, बिल के साथ', en: 'Company warranty, with the bill' },
  'Confirm karna hai': { hi: 'कन्फर्म करना है', en: 'Needs confirmation' },
  'Copy karein': { hi: 'कॉपी करें', en: 'Copy' },
  'Counter / default rate': { hi: 'काउंटर / आम रेट', en: 'Counter / default rate' },
  'Credit limit': { hi: 'उधार की हद', en: 'Credit limit' },
  'CSV chunein': { hi: 'CSV चुनें', en: 'Choose CSV' },
  'CSV se items import karein': { hi: 'CSV से आइटम इम्पोर्ट करें', en: 'Import items from CSV' },
  Date: { hi: 'तारीख', en: 'Date' },
  'De diye': { hi: 'दे दिए', en: 'Paid out' },
  'Default settings': { hi: 'आम सेटिंग', en: 'Default settings' },
  Dekhna: { hi: 'देखना', en: 'View' },
  Delete: { hi: 'मिटाएं', en: 'Delete' },
  'Dena hai (suppliers ko)': { hi: 'देना है (सप्लायर को)', en: 'Payable (to suppliers)' },
  Description: { hi: 'ब्यौरा', en: 'Description' },
  Dikhayein: { hi: 'दिखाएं', en: 'Show' },
  'Din wala safed ya raat wala kaala': { hi: 'दिन वाला सफेद या रात वाला काला', en: 'Light for day or dark for night' },
  Discount: { hi: 'छूट', en: 'Discount' },
  Diya: { hi: 'दिया', en: 'Paid' },
  'Do minute me apni dukaan set kar lein': { hi: 'दो मिनट में अपनी दुकान सेट कर लें', en: 'Set up your shop in two minutes' },
  'Dukaan ka naam': { hi: 'दुकान का नाम', en: 'Shop name' },
  'Dukaan ke log': { hi: 'दुकान के लोग', en: 'Shop staff' },
  'Dukaan ke malik ne aapko is hisse ki ijazat nahi di hai. Zarurat ho to unse kahiye.': { hi: 'दुकान के मालिक ने आपको इस हिस्से की इजाज़त नहीं दी है। ज़रूरत हो तो उनसे कहिए।', en: 'The shop owner has not given you access to this section. Ask them if you need it.' },
  'Dukaan ke malik se nayi link mangwa lijiye.': { hi: 'दुकान के मालिक से नई लिंक मंगवा लीजिए।', en: 'Ask the shop owner for a fresh link.' },
  'Dukaan ki detail': { hi: 'दुकान की जानकारी', en: 'Shop details' },
  'Dukaan ki detail, GST, staff aur backup': { hi: 'दुकान की जानकारी, GST, स्टाफ और बैकअप', en: 'Shop details, GST, staff and backup' },
  Edit: { hi: 'बदलें', en: 'Edit' },
  Email: { hi: 'ईमेल', en: 'Email' },
  'Entry karein': { hi: 'एंट्री करें', en: 'Make entry' },
  Error: { hi: 'गड़बड़', en: 'Error' },
  'Excel me kholne ke liye': { hi: 'एक्सेल में खोलने के लिए', en: 'To open in Excel' },
  'Excel/Google Sheet se seedha 500 item ek saath': { hi: 'एक्सेल/गूगल शीट से सीधे 500 आइटम एक साथ', en: 'Straight from Excel/Google Sheets — 500 items at once' },
  Export: { hi: 'एक्सपोर्ट', en: 'Export' },
  'File padhi ja rahi hai...': { hi: 'फाइल पढ़ी जा रही है...', en: 'Reading the file...' },
  'Filter hatayein': { hi: 'फिल्टर हटाएं', en: 'Clear filters' },
  'Gaadi number / kis truck se aaya': { hi: 'गाड़ी नंबर / किस ट्रक से आया', en: 'Vehicle number / which truck it came on' },
  'Galat rate lag gaya tha': { hi: 'गलत रेट लग गया था', en: 'Wrong rate was applied' },
  'Ghata (−)': { hi: 'घटा (−)', en: 'Reduced (−)' },
  'Godown me kahan rakha hai': { hi: 'गोदाम में कहां रखा है', en: 'Where it is kept in the godown' },
  'GST ke khaane dekhne ke liye table ko ungli se side me khiskayein →': { hi: 'GST के खाने देखने के लिए टेबल को उंगली से बगल में खिसकाएं →', en: 'Swipe the table sideways to see the GST columns →' },
  'GST rate': { hi: 'GST रेट', en: 'GST rate' },
  'GSTIN (agar hai)': { hi: 'GSTIN (अगर है)', en: 'GSTIN (if any)' },
  'Haan, cancel karein': { hi: 'हां, कैंसिल करें', en: 'Yes, cancel it' },
  'Haan, hatayein': { hi: 'हां, हटाएं', en: 'Yes, remove it' },
  'Har aadmi ka apna login, apni ijazat aur apni hadd': { hi: 'हर आदमी का अपना लॉगिन, अपनी इजाज़त और अपनी हद', en: 'Each person gets their own login, permissions and limits' },
  'Har invoice ke upar chhapega': { hi: 'हर बिल के ऊपर छपेगा', en: 'Prints at the top of every invoice' },
  'Har item ke saamne abhi ka stock bhi dikha hai': { hi: 'हर आइटम के सामने अभी का स्टॉक भी दिखा है', en: 'Current stock is shown next to each item' },
  'Har mangal ko aata hai / cash me hi deta hai': { hi: 'हर मंगल को आता है / कैश में ही देता है', en: 'Comes every Tuesday / pays only in cash' },
  'Hat jayega': { hi: 'हट जाएगा', en: 'Will be removed' },
  Hatayein: { hi: 'हटाएं', en: 'Remove' },
  'Hinglish matlab jaisa abhi hai — Hindi ke shabd English akshar me. Jo shabd abhi anuvaad nahi hue, wo Hinglish me hi rahenge.': { hi: 'हिंग्लिश मतलब जैसा अभी है — हिन्दी के शब्द अंग्रेजी अक्षरों में। जो शब्द अभी अनुवाद नहीं हुए, वो हिंग्लिश में ही रहेंगे।', en: 'Hinglish means as it is today — Hindi words in English letters. Words not translated yet will stay in Hinglish.' },
  Hisaab: { hi: 'हिसाब', en: 'Ledger' },
  'Hisaab barabar': { hi: 'हिसाब बराबर', en: 'All settled' },
  'HSN wise summary': { hi: 'HSN के हिसाब से ब्यौरा', en: 'HSN wise summary' },
  Import: { hi: 'इम्पोर्ट', en: 'Import' },
  'Inka login turant band ho jayega. Inke naam wale retailer sabke ho jayenge — data kuch nahi mitega.': { hi: 'इनका लॉगिन तुरंत बंद हो जाएगा। इनके नाम वाले रिटेलर सबके हो जाएंगे — डेटा कुछ नहीं मिटेगा।', en: 'Their login stops at once. Retailers assigned to them become shared — no data is deleted.' },
  'Inko phone karna banta hai': { hi: 'इनको फोन करना बनता है', en: 'Worth giving them a call' },
  'Invite link se bana hua login': { hi: 'इनवाइट लिंक से बना हुआ लॉगिन', en: 'Login created from an invite link' },
  'Invoice ke terms & conditions': { hi: 'बिल की शर्तें', en: 'Invoice terms and conditions' },
  'Invoice number prefix': { hi: 'बिल नंबर का उपसर्ग', en: 'Invoice number prefix' },
  'Invoice pe yahi address aayega': { hi: 'बिल पर यही पता आएगा', en: 'This address prints on the invoice' },
  Invoices: { hi: 'बिल', en: 'Invoices' },
  'Is device se nikal jayein': { hi: 'इस डिवाइस से निकल जाएं', en: 'Sign out of this device' },
  'Is duration me koi lena-dena nahi': { hi: 'इस अवधि में कोई लेन-देन नहीं', en: 'No transactions in this period' },
  'Is duration me kuch nahi mila': { hi: 'इस अवधि में कुछ नहीं मिला', en: 'Nothing found in this period' },
  'Is item ka karan (marzi se)': { hi: 'इस आइटम का कारण (मर्ज़ी से)', en: 'Reason for this item (optional)' },
  'Is item ka total': { hi: 'इस आइटम का कुल', en: 'Total for this item' },
  'Is mahine': { hi: 'इस महीने', en: 'This month' },
  'Is mahine wapas aaya': { hi: 'इस महीने वापस आया', en: 'Returned to us this month' },
  'Is mahine wapas bheja': { hi: 'इस महीने वापस भेजा', en: 'Sent back this month' },
  'Is order ka bill ban chuka hai': { hi: 'इस ऑर्डर का बिल बन चुका है', en: 'This order has already been billed' },
  'Is purchase se kitna maal badha': { hi: 'इस खरीद से कितना माल बढ़ा', en: 'How much stock this purchase added' },
  'Isi format me apne items bhar kar wapas upload karein. Column: name (zaroori), sku, category, unit, purchasePrice, salePrice, wholesalePrice, stockQty, lowStockAt, hsn, gstRate.': { hi: 'इसी फॉर्मेट में अपने आइटम भर कर वापस अपलोड करें। कॉलम: name (ज़रूरी), sku, category, unit, purchasePrice, salePrice, wholesalePrice, stockQty, lowStockAt, hsn, gstRate.', en: 'Fill your items in this same format and upload it back. Columns: name (required), sku, category, unit, purchasePrice, salePrice, wholesalePrice, stockQty, lowStockAt, hsn, gstRate.' },
  'Isi number se login hoga': { hi: 'इसी नंबर से लॉगिन होगा', en: 'This number will be used to log in' },
  'Isi se tay hoga CGST+SGST lagega ya IGST': { hi: 'इसी से तय होगा CGST+SGST लगेगा या IGST', en: 'This decides whether CGST+SGST or IGST applies' },
  'Iske orders': { hi: 'इसके ऑर्डर', en: 'Their orders' },
  'Isne invite link se account nahi banaya hai. Link WhatsApp pe bhej dein — isi phone number se register karne par ye entry apne aap jud jayegi.': { hi: 'इसने इनवाइट लिंक से अकाउंट नहीं बनाया है। लिंक WhatsApp पर भेज दें — इसी फोन नंबर से रजिस्टर करने पर ये एंट्री अपने आप जुड़ जाएगी।', en: 'They have not created an account from the invite link. Send them the link — registering with this same phone number links this entry automatically.' },
  'Isse aaya maal': { hi: 'इससे आया माल', en: 'Goods received from them' },
  'Isse hi login karenge': { hi: 'इसी से लॉगिन करेंगे', en: 'This is what they log in with' },
  Item: { hi: 'आइटम', en: 'Item' },
  'Item dhoondhein': { hi: 'आइटम ढूंढें', en: 'Find an item' },
  'Item dhundhein': { hi: 'आइटम ढूंढें', en: 'Find an item' },
  'Item dhundhein...': { hi: 'आइटम ढूंढें...', en: 'Find an item...' },
  'Item hat gaya': { hi: 'आइटम हट गया', en: 'Item removed' },
  'Item ka naam': { hi: 'आइटम का नाम', en: 'Item name' },
  'Item ka purchase price is bill ke rate se badal jayega': { hi: 'आइटम का खरीद रेट इस बिल के रेट से बदल जाएगा', en: 'The item purchase price will be updated to this bill rate' },
  Items: { hi: 'आइटम', en: 'Items' },
  'Items ko group karne ke liye': { hi: 'आइटम को समूह में रखने के लिए', en: 'To group your items' },
  'Itne se kam hone par alert': { hi: 'इससे कम होने पर चेतावनी', en: 'Alert when it falls below this' },
  'Itne se kam stock par alert aayega': { hi: 'इससे कम स्टॉक पर चेतावनी आएगी', en: 'You will be alerted below this stock' },
  'Jaise: 2 piece me awaaz aa rahi thi': { hi: 'जैसे: 2 पीस में आवाज़ आ रही थी', en: 'For example: 2 pieces were making noise' },
  'Jaise: account me paisa nahi aaya': { hi: 'जैसे: अकाउंट में पैसा नहीं आया', en: 'For example: money never reached the account' },
  'Jaise: Ramesh ke haath bheja': { hi: 'जैसे: रमेश के हाथ भेजा', en: 'For example: sent with Ramesh' },
  'Jitna bhej sakte hain utna kar dein — 0 karne pe item order se hat jayega': { hi: 'जितना भेज सकते हैं उतना कर दें — 0 करने पर आइटम ऑर्डर से हट जाएगा', en: 'Set what you can actually send — setting 0 removes the item from the order' },
  'Jo abhi tak istemal nahi hui': { hi: 'जो अभी तक इस्तेमाल नहीं हुई', en: 'Not used yet' },
  'Jo item aaya hai, quantity aur rate ke saath': { hi: 'जो आइटम आया है, मात्रा और रेट के साथ', en: 'Items received, with quantity and rate' },
  'Jo item kisi purane bill ya purchase me hain wo delete nahi honge — sirf hide ho jayenge, taaki purane record kharab na hon.': { hi: 'जो आइटम किसी पुराने बिल या खरीद में हैं वो डिलीट नहीं होंगे — सिर्फ छुप जाएंगे, ताकि पुराने रिकॉर्ड खराब न हों।', en: 'Items used in an old bill or purchase are not deleted — only hidden, so old records stay intact.' },
  'Jud jayein': { hi: 'जुड़ जाएं', en: 'Join' },
  'Kaam ka record': { hi: 'काम का रिकॉर्ड', en: 'Activity record' },
  Kab: { hi: 'कब', en: 'When' },
  'Kab se': { hi: 'कब से', en: 'From' },
  'Kab tak': { hi: 'कब तक', en: 'To' },
  'Kaise dekhein': { hi: 'कैसे देखें', en: 'How to view' },
  'Kaise mila': { hi: 'कैसे मिला', en: 'How received' },
  'kal se': { hi: 'कल से', en: 'since yesterday' },
  'Kam bache': { hi: 'कम बचे', en: 'Running low' },
  'Kam se kam 6 character': { hi: 'कम से कम 6 अक्षर', en: 'At least 6 characters' },
  'Kam se kam 6 character. Ye sirf aapko pata rahega — malik ko bhi nahi.': { hi: 'कम से कम 6 अक्षर। ये सिर्फ आपको पता रहेगा — मालिक को भी नहीं।', en: 'At least 6 characters. Only you will know it — not even the owner.' },
  'Kam se kam order': { hi: 'कम से कम ऑर्डर', en: 'Minimum order' },
  Karan: { hi: 'कारण', en: 'Reason' },
  'Karan:': { hi: 'कारण:', en: 'Reason:' },
  'Kaunsa maal wapas': { hi: 'कौन सा माल वापस', en: 'Which goods are being returned' },
  'Kaunse items pe': { hi: 'किन आइटम पर', en: 'On which items' },
  'khaas rate': { hi: 'खास रेट', en: 'special rate' },
  'Khaas rate': { hi: 'खास रेट', en: 'Special rate' },
  'Khali chhod do to poora udhaar': { hi: 'खाली छोड़ दो तो पूरा उधार', en: 'Leave blank for full credit' },
  'Khali chhodein to jitna marzi': { hi: 'खाली छोड़ें तो जितना मर्ज़ी', en: 'Leave blank for no limit' },
  Khata: { hi: 'खाता', en: 'Ledger' },
  'Khata khul raha hai...': { hi: 'खाता खुल रहा है...', en: 'Opening the ledger...' },
  'Khata wapas pehle jaisa ho jayega aur bill dobara udhaar dikhne lagega. Ye wapas nahi hota.': { hi: 'खाता वापस पहले जैसा हो जाएगा और बिल दोबारा उधार दिखने लगेगा। ये वापस नहीं होता।', en: 'The ledger goes back to how it was and the bill shows as unpaid again. This cannot be undone.' },
  Khatam: { hi: 'खत्म', en: 'Out of stock' },
  Kholein: { hi: 'खोलें', en: 'Open' },
  'Kis liye (sirf aapki yaad ke liye)': { hi: 'किस लिए (सिर्फ आपकी याद के लिए)', en: 'What for (just for your own reference)' },
  'Kiska bill': { hi: 'किसका बिल', en: 'Whose bill' },
  'Kiska paisa': { hi: 'किसका पैसा', en: 'Whose payment' },
  'Kisne kiya': { hi: 'किसने किया', en: 'Who did it' },
  'Kisse aaya': { hi: 'किससे आया', en: 'Received from' },
  'Kisse kitna lena hai, kisko kitna dena hai — sab ek jagah': { hi: 'किससे कितना लेना है, किसको कितना देना है — सब एक जगह', en: 'Who owes you and whom you owe — all in one place' },
  Kitna: { hi: 'कितना', en: 'How much' },
  'Kitne din chalegi': { hi: 'कितने दिन चलेगी', en: 'Valid for how many days' },
  'Kitne din ki': { hi: 'कितने दिन की', en: 'For how many days' },
  'Koi active retailer nahi mila': { hi: 'कोई चालू रिटेलर नहीं मिला', en: 'No active retailer found' },
  'Koi category nahi': { hi: 'कोई श्रेणी नहीं', en: 'No categories' },
  'koi hadd nahi': { hi: 'कोई हद नहीं', en: 'no limit' },
  'Koi item nahi mila': { hi: 'कोई आइटम नहीं मिला', en: 'No items found' },
  'Koi khaas baat jo yaad rakhni ho': { hi: 'कोई खास बात जो याद रखनी हो', en: 'Anything special worth remembering' },
  'Koi movement record nahi': { hi: 'कोई हलचल दर्ज नहीं', en: 'No movement recorded' },
  'Koi supplier nahi mila': { hi: 'कोई सप्लायर नहीं मिला', en: 'No suppliers found' },
  Kul: { hi: 'कुल', en: 'Total' },
  'Kul badha': { hi: 'कुल बढ़ा', en: 'Total added' },
  'Kul bills': { hi: 'कुल बिल', en: 'Total bills' },
  'Kul dena': { hi: 'कुल देना', en: 'Total payable' },
  'Kul entry': { hi: 'कुल एंट्री', en: 'Total entries' },
  'Kul ghata': { hi: 'कुल घटा', en: 'Total reduced' },
  'Kul item': { hi: 'कुल आइटम', en: 'Total items' },
  'Kul items': { hi: 'कुल आइटम', en: 'Total items' },
  'Kul kharch': { hi: 'कुल खर्च', en: 'Total spent' },
  'Kul maal': { hi: 'कुल माल', en: 'Total goods' },
  'Kul purchases': { hi: 'कुल खरीद', en: 'Total purchases' },
  'Kul rows': { hi: 'कुल पंक्तियां', en: 'Total rows' },
  'Kul sale': { hi: 'कुल सेल', en: 'Total sales' },
  'Kya hua': { hi: 'क्या हुआ', en: 'What happened' },
  'Kya karna hai': { hi: 'क्या करना है', en: 'What to do' },
  'Kya kya hua': { hi: 'क्या क्या हुआ', en: 'What all happened' },
  'Kya wajah batayein': { hi: 'क्या वजह बताएं', en: 'Tell them the reason' },
  'Kyun? (marzi)': { hi: 'क्यों? (मर्ज़ी)', en: 'Why? (optional)' },
  'Lena hai (retailers se)': { hi: 'लेना है (रिटेलर से)', en: 'Receivable (from retailers)' },
  'Limit paar': { hi: 'हद पार', en: 'Over limit' },
  'Limit se upar': { hi: 'हद से ऊपर', en: 'Above the limit' },
  Link: { hi: 'लिंक', en: 'Link' },
  'Link banayein': { hi: 'लिंक बनाएं', en: 'Create link' },
  'Link bhej dijiye — aane wala khud apna naam aur password banayega. Aapko uska password kabhi pata nahi chalega.': { hi: 'लिंक भेज दीजिए — आने वाला खुद अपना नाम और पासवर्ड बनाएगा। आपको उसका पासवर्ड कभी पता नहीं चलेगा।', en: 'Just send the link — they will set their own name and password. You will never see their password.' },
  'Link chalu rakhein': { hi: 'लिंक चालू रखें', en: 'Keep the link active' },
  'Link kaam nahi kar raha': { hi: 'लिंक काम नहीं कर रहा', en: 'This link is not working' },
  'Link kaam nahi kar rahi': { hi: 'लिंक काम नहीं कर रही', en: 'This link is not working' },
  'Link se bulayein': { hi: 'लिंक से बुलाएं', en: 'Invite by link' },
  'Link tayyar hai': { hi: 'लिंक तैयार है', en: 'Link is ready' },
  'List, approve/block, party-wise rate aur khata — sab Retailers page pe': { hi: 'लिस्ट, अप्रूव/ब्लॉक, पार्टी-वार रेट और खाता — सब रिटेलर पेज पर', en: 'List, approve/block, party-wise rates and ledger — all on the Retailers page' },
  Login: { hi: 'लॉगिन', en: 'Login' },
  'Login chalu hai': { hi: 'लॉगिन चालू है', en: 'Login is active' },
  'Login karein': { hi: 'लॉगिन करें', en: 'Log in' },
  'Login naam': { hi: 'लॉगिन नाम', en: 'Login name' },
  'Login number': { hi: 'लॉगिन नंबर', en: 'Login number' },
  'Login page pe jayein': { hi: 'लॉगिन पेज पर जाएं', en: 'Go to the login page' },
  Logo: { hi: 'लोगो', en: 'Logo' },
  Logout: { hi: 'लॉगआउट', en: 'Log out' },
  'Low stock': { hi: 'कम स्टॉक', en: 'Low stock' },
  'Low stock warning': { hi: 'कम स्टॉक की चेतावनी', en: 'Low stock warning' },
  Maal: { hi: 'माल', en: 'Goods' },
  'Maal wapas aaya': { hi: 'माल वापस आया', en: 'Goods returned to us' },
  'Maal wapas aaya ya bheja — stock aur khata dono apne aap theek ho jate hain': { hi: 'माल वापस आया या भेजा — स्टॉक और खाता दोनों अपने आप ठीक हो जाते हैं', en: 'Goods returned in or sent back — both stock and ledger fix themselves' },
  'Maal wapas bheja': { hi: 'माल वापस भेजा', en: 'Goods sent back' },
  'Maal wapas nahi hoga': { hi: 'माल वापस नहीं होगा', en: 'Goods are not returnable' },
  'Maal wapas nahi hoga. Payment 30 din me.': { hi: 'माल वापस नहीं होगा। पेमेंट 30 दिन में।', en: 'Goods are not returnable. Payment within 30 days.' },
  'Mahine ka hisaab, CA ko dene layak': { hi: 'महीने का हिसाब, CA को देने लायक', en: 'Monthly summary, ready to hand to your CA' },
  Mangi: { hi: 'मांगी', en: 'Ordered' },
  Menu: { hi: 'मेन्यू', en: 'Menu' },
  'Menu band karein': { hi: 'मेन्यू बंद करें', en: 'Close menu' },
  'Meri dukaan GST registered hai': { hi: 'मेरी दुकान GST रजिस्टर्ड है', en: 'My shop is GST registered' },
  'Mil gaya': { hi: 'मिल गया', en: 'Received' },
  'Model / Serial number': { hi: 'मॉडल / सीरियल नंबर', en: 'Model / Serial number' },
  'MongoDB Atlas use kar rahe hain to wahan settings me automatic backup on kar dijiye. Uske alawa mahine me ek baar upar wali JSON file bhi le liya karein — dono alag alag cheezein hain.': { hi: 'MongoDB Atlas इस्तेमाल कर रहे हैं तो वहां सेटिंग में अपने आप बैकअप चालू कर दीजिए। उसके अलावा महीने में एक बार ऊपर वाली JSON फाइल भी ले लिया करें — दोनों अलग अलग चीज़ें हैं।', en: 'If you use MongoDB Atlas, turn on automatic backup in its settings. Also take the JSON file above once a month — the two are different things.' },
  Naam: { hi: 'नाम', en: 'Name' },
  'Naam badlein': { hi: 'नाम बदलें', en: 'Rename' },
  'Naam ya phone se dhoondhein': { hi: 'नाम या फोन से ढूंढें', en: 'Search by name or phone' },
  'Naam ya phone...': { hi: 'नाम या फोन...', en: 'Name or phone...' },
  'Naam, brand, SKU, model ya barcode...': { hi: 'नाम, ब्रांड, SKU, मॉडल या बारकोड...', en: 'Name, brand, SKU, model or barcode...' },
  'Naam, dukaan ya phone se dhundhein...': { hi: 'नाम, दुकान या फोन से ढूंढें...', en: 'Search by name, shop or phone...' },
  'Nahi mila': { hi: 'नहीं मिला', en: 'Not found' },
  'Naya aadmi': { hi: 'नया आदमी', en: 'New person' },
  'Naya bill': { hi: 'नया बिल', en: 'New bill' },
  'Naya item': { hi: 'नया आइटम', en: 'New item' },
  'Naya link banayein': { hi: 'नया लिंक बनाएं', en: 'Create a new link' },
  'Naya link banayein?': { hi: 'नया लिंक बनाएं?', en: 'Create a new link?' },
  'Naya password': { hi: 'नया पासवर्ड', en: 'New password' },
  'Naya password dobara': { hi: 'नया पासवर्ड दोबारा', en: 'New password again' },
  'Naya return': { hi: 'नया रिटर्न', en: 'New return' },
  'Naya total': { hi: 'नया कुल', en: 'New total' },
  Naye: { hi: 'नए', en: 'New' },
  'Naye order': { hi: 'नए ऑर्डर', en: 'New orders' },
  'Naye retailer jodne ka link': { hi: 'नए रिटेलर जोड़ने का लिंक', en: 'Link for adding new retailers' },
  Nayi: { hi: 'नई', en: 'New' },
  'Nayi category': { hi: 'नई श्रेणी', en: 'New category' },
  'Nayi category ka naam': { hi: 'नई श्रेणी का नाम', en: 'New category name' },
  'Nayi purchase': { hi: 'नई खरीद', en: 'New purchase' },
  'Neeche list me laal me dikha hai. "Quantity badlein" se utna kar dein jitna bhej sakte hain — retailer ko apne aap pata chal jayega.': { hi: 'नीचे लिस्ट में लाल में दिखा है। "Quantity badlein" से उतना कर दें जितना भेज सकते हैं — रिटेलर को अपने आप पता चल जाएगा।', en: 'Shown in red in the list below. Use "Change quantity" to set what you can actually send — the retailer is informed automatically.' },
  'Neeche wala menu': { hi: 'नीचे वाला मेन्यू', en: 'Bottom menu' },
  Net: { hi: 'शुद्ध', en: 'Net' },
  Note: { hi: 'नोट', en: 'Note' },
  'Note (bill pe chhapega)': { hi: 'नोट (बिल पर छपेगा)', en: 'Note (prints on the bill)' },
  'Note (marzi se)': { hi: 'नोट (मर्ज़ी से)', en: 'Note (optional)' },
  'Note number, bill ya party...': { hi: 'नोट नंबर, बिल या पार्टी...', en: 'Note number, bill or party...' },
  'Note pe chhapega — baad me yaad rehta hai ki kyun wapas hua': { hi: 'नोट पर छपेगा — बाद में याद रहता है कि क्यों वापस हुआ', en: 'Prints on the note — later you remember why it came back' },
  Notifications: { hi: 'सूचनाएं', en: 'Notifications' },
  'Number me dekhein': { hi: 'संख्या में देखें', en: 'View as numbers' },
  'Number ya bill se dhundhein...': { hi: 'नंबर या बिल से ढूंढें...', en: 'Search by number or bill...' },
  'Off karne par ye item retailer ke catalog me nahi aayega': { hi: 'बंद करने पर ये आइटम रिटेलर के कैटलॉग में नहीं आएगा', en: 'When off, this item will not appear in the retailer catalog' },
  'On karne par link se aane wala har retailer turant catalog dekh sakega': { hi: 'चालू करने पर लिंक से आने वाला हर रिटेलर तुरंत कैटलॉग देख सकेगा', en: 'When on, every retailer joining by link can see the catalog immediately' },
  'Opening stock': { hi: 'शुरुआती स्टॉक', en: 'Opening stock' },
  Order: { hi: 'ऑर्डर', en: 'Order' },
  'Order ka saman': { hi: 'ऑर्डर का सामान', en: 'Order items' },
  'Order ke against': { hi: 'ऑर्डर के बदले', en: 'Against order' },
  'Order number ya retailer...': { hi: 'ऑर्डर नंबर या रिटेलर...', en: 'Order number or retailer...' },
  'Order se detail aa rahi hai...': { hi: 'ऑर्डर से जानकारी आ रही है...', en: 'Pulling details from the order...' },
  Orders: { hi: 'ऑर्डर', en: 'Orders' },
  'Pack ho rahe': { hi: 'पैक हो रहे', en: 'Being packed' },
  'Packet pe chhapa hua rate — retailer ko dikhega': { hi: 'पैकेट पर छपा हुआ रेट — रिटेलर को दिखेगा', en: 'Printed rate on the packet — visible to the retailer' },
  'Paisa apne aap sabse purane bill pe lagega. Zyada hua to advance jama rahega.': { hi: 'पैसा अपने आप सबसे पुराने बिल पर लगेगा। ज़्यादा हुआ तो एडवांस जमा रहेगा।', en: 'Money is applied to the oldest bill first. Anything extra stays as advance.' },
  'Paisa entry': { hi: 'पैसा एंट्री', en: 'Payment entry' },
  'Part number ya serial — dono chalega': { hi: 'पार्ट नंबर या सीरियल — दोनों चलेगा', en: 'Part number or serial — either works' },
  Password: { hi: 'पासवर्ड', en: 'Password' },
  'Password badlein': { hi: 'पासवर्ड बदलें', en: 'Change password' },
  'Password banayein': { hi: 'पासवर्ड बनाएं', en: 'Set a password' },
  'Payment no, party, UTR...': { hi: 'पेमेंट नंबर, पार्टी, UTR...', en: 'Payment no, party, UTR...' },
  'Payment reject karein?': { hi: 'पेमेंट रिजेक्ट करें?', en: 'Reject this payment?' },
  Payments: { hi: 'पेमेंट', en: 'Payments' },
  'Peeche jayein': { hi: 'पीछे जाएं', en: 'Go back' },
  Pehchan: { hi: 'पहचान', en: 'Identity' },
  'Pehla bill': { hi: 'पहला बिल', en: 'First bill' },
  'Pehla item add karein': { hi: 'पहला आइटम जोड़ें', en: 'Add your first item' },
  'Pehla return': { hi: 'पहला रिटर्न', en: 'First return' },
  'Pehle upar State chun lein — GSTIN uske saath match kiya jayega.': { hi: 'पहले ऊपर राज्य चुन लें — GSTIN उसी से मिलाया जाएगा।', en: 'Pick the state above first — the GSTIN is checked against it.' },
  'Pehli entry': { hi: 'पहली एंट्री', en: 'First entry' },
  'Pehli purchase': { hi: 'पहली खरीद', en: 'First purchase' },
  Phone: { hi: 'फोन', en: 'Phone' },
  'Phone number': { hi: 'फोन नंबर', en: 'Phone number' },
  'Pichla page': { hi: 'पिछला पेज', en: 'Previous page' },
  Pincode: { hi: 'पिनकोड', en: 'Pincode' },
  'PNG, JPG ya WEBP · 3 MB tak': { hi: 'PNG, JPG या WEBP · 3 MB तक', en: 'PNG, JPG or WEBP · up to 3 MB' },
  'Poora app chhota ya bada ho jayega': { hi: 'पूरी ऐप छोटी या बड़ी हो जाएगी', en: 'The whole app becomes smaller or bigger' },
  'Poora backup': { hi: 'पूरा बैकअप', en: 'Full backup' },
  'Poora data download karein': { hi: 'पूरा डेटा डाउनलोड करें', en: 'Download all data' },
  'Poora menu': { hi: 'पूरा मेन्यू', en: 'Full menu' },
  'Poori detail': { hi: 'पूरी जानकारी', en: 'Full details' },
  'Preview me sirf pehli 200 rows dikhayi hain — import saari hongi.': { hi: 'झलक में सिर्फ पहली 200 पंक्तियां दिखाई हैं — इम्पोर्ट सारी होंगी।', en: 'Only the first 200 rows are previewed — all of them will be imported.' },
  Price: { hi: 'रेट', en: 'Price' },
  Print: { hi: 'प्रिंट', en: 'Print' },
  'Print / PDF': { hi: 'प्रिंट / PDF', en: 'Print / PDF' },
  'Print dabate hi sirf bill chhapega — sidebar aur buttons nahi. PDF chahiye to print window me "Save as PDF" chun lein.': { hi: 'प्रिंट दबाते ही सिर्फ बिल छपेगा — साइडबार और बटन नहीं। PDF चाहिए तो प्रिंट विंडो में "Save as PDF" चुन लें।', en: 'Pressing print prints only the bill — not the sidebar or buttons. For a PDF, pick "Save as PDF" in the print window.' },
  'Purana hisaab': { hi: 'पुराना हिसाब', en: 'Opening balance' },
  'Purana link turant band ho jayega. Jinko purana link bheja tha wo register nahi kar payenge — unhe naya link dobara bhejna padega. Jo retailers pehle se jud chuke hain unpe koi asar nahi hoga.': { hi: 'पुराना लिंक तुरंत बंद हो जाएगा। जिनको पुराना लिंक भेजा था वो रजिस्टर नहीं कर पाएंगे — उन्हें नया लिंक दोबारा भेजना पड़ेगा। जो रिटेलर पहले से जुड़ चुके हैं उन पर कोई असर नहीं होगा।', en: 'The old link stops working at once. Anyone you sent it to will not be able to register — you will have to send them the new link. Retailers who already joined are unaffected.' },
  'Purana password': { hi: 'पुराना पासवर्ड', en: 'Old password' },
  'Purani hatayein': { hi: 'पुरानी हटाएं', en: 'Clear old ones' },
  Purchase: { hi: 'खरीद', en: 'Purchase' },
  'Purchase price': { hi: 'खरीद रेट', en: 'Purchase price' },
  'Purchase price update karein': { hi: 'खरीद रेट अपडेट करें', en: 'Update purchase price' },
  Purchases: { hi: 'खरीद', en: 'Purchases' },
  Qty: { hi: 'मात्रा', en: 'Qty' },
  'Quantity badlein': { hi: 'मात्रा बदलें', en: 'Change quantity' },
  'Rack / jagah': { hi: 'रैक / जगह', en: 'Rack / location' },
  'Rad karein': { hi: 'रद्द करें', en: 'Cancel it' },
  Rate: { hi: 'रेट', en: 'Rate' },
  'Rate lagne ka order': { hi: 'रेट लगने का क्रम', en: 'Order in which rates apply' },
  'Rate retailer ke hisaab se apne aap aata hai': { hi: 'रेट रिटेलर के हिसाब से अपने आप आता है', en: 'The rate is picked automatically for that retailer' },
  'Rate round karein': { hi: 'रेट राउंड करें', en: 'Round the rate' },
  'Record apne aap banta hai — ise koi mita nahi sakta, malik bhi nahi.': { hi: 'रिकॉर्ड अपने आप बनता है — इसे कोई मिटा नहीं सकता, मालिक भी नहीं।', en: 'The record is written automatically — nobody can erase it, not even the owner.' },
  'Register karein': { hi: 'रजिस्टर करें', en: 'Register' },
  'Rehne dein': { hi: 'रहने दें', en: 'Cancel' },
  'Reject karein': { hi: 'रिजेक्ट करें', en: 'Reject' },
  Reports: { hi: 'रिपोर्ट', en: 'Reports' },
  Retailer: { hi: 'रिटेलर', en: 'Retailer' },
  'Retailer chunein': { hi: 'रिटेलर चुनें', en: 'Choose retailer' },
  'Retailer ho? Apne wholesaler ka bheja hua link kholo.': { hi: 'रिटेलर हैं? अपने होलसेलर का भेजा हुआ लिंक खोलें।', en: 'Are you a retailer? Open the link your wholesaler sent you.' },
  'Retailer invite link': { hi: 'रिटेलर इनवाइट लिंक', en: 'Retailer invite link' },
  'Retailer isse kam order nahi kar payega (0 = koi rok nahi)': { hi: 'रिटेलर इससे कम ऑर्डर नहीं कर पाएगा (0 = कोई रोक नहीं)', en: 'The retailer cannot order less than this (0 = no restriction)' },
  'Retailer ka note:': { hi: 'रिटेलर का नोट:', en: 'Retailer note:' },
  'Retailer ko kya batayein': { hi: 'रिटेलर को क्या बताएं', en: 'What to tell the retailer' },
  'Retailer ko paisa bhejte waqt yahi naam dikhega': { hi: 'रिटेलर को पैसा भेजते वक्त यही नाम दिखेगा', en: 'This is the name the retailer sees while paying' },
  'Retailer ko QR aur "UPI app kholein" ka button dikhega. Paisa bhejne ke baad wo "bhej diya" dabayega — aap apna account dekh kar confirm karenge, tabhi khate me lagega.': { hi: 'रिटेलर को QR और "UPI app kholein" का बटन दिखेगा। पैसा भेजने के बाद वो "भेज दिया" दबाएगा — आप अपना अकाउंट देख कर कन्फर्म करेंगे, तभी खाते में लगेगा।', en: 'The retailer sees a QR and an "Open UPI app" button. After paying they tap "sent" — it only hits the ledger once you check your account and confirm.' },
  'Retailer ko turant khabar chali jayegi. Cancel kiya hua order wapas nahi aata.': { hi: 'रिटेलर को तुरंत खबर चली जाएगी। कैंसिल किया हुआ ऑर्डर वापस नहीं आता।', en: 'The retailer is notified immediately. A cancelled order cannot be brought back.' },
  'Retailer ko yahi message jayega': { hi: 'रिटेलर को यही संदेश जाएगा', en: 'This is the message the retailer gets' },
  'Retailer ne bheja hai — apna account check karke haan/na karein': { hi: 'रिटेलर ने भेजा है — अपना अकाउंट देख कर हां/ना करें', en: 'Sent by the retailer — check your account, then accept or reject' },
  'Retailer se chhupa': { hi: 'रिटेलर से छुपा', en: 'Hidden from retailer' },
  'Retailer se paisa mile ya supplier ko dein — yahin entry karein, khata apne aap update ho jayega.': { hi: 'रिटेलर से पैसा मिले या सप्लायर को दें — यहीं एंट्री करें, खाता अपने आप अपडेट हो जाएगा।', en: 'Money received from a retailer or paid to a supplier — enter it here and the ledger updates itself.' },
  'Retailers apne app se order bhejenge to yahan turant dikh jayenge — aur bell bhi bajegi.': { hi: 'रिटेलर अपने ऐप से ऑर्डर भेजेंगे तो यहां तुरंत दिख जाएंगे — और घंटी भी बजेगी।', en: 'When retailers order from their app it shows up here at once — and the bell rings too.' },
  'Retailers ka poora management': { hi: 'रिटेलर का पूरा प्रबंध', en: 'Full retailer management' },
  'Retailers ke bheje hue order': { hi: 'रिटेलर के भेजे हुए ऑर्डर', en: 'Orders sent by retailers' },
  'Retailers ko dikhayein': { hi: 'रिटेलर को दिखाएं', en: 'Show to retailers' },
  'Retailers ko yahi dikhega': { hi: 'रिटेलर को यही दिखेगा', en: 'This is what retailers see' },
  Return: { hi: 'रिटर्न', en: 'Return' },
  Role: { hi: 'पद', en: 'Role' },
  'Role chunte hi uski aam ijazat lag jati hai — "Ijazat" me jaakar ghata-badha sakte hain.': { hi: 'पद चुनते ही उसकी आम इजाज़त लग जाती है — "Ijazat" में जाकर घटा-बढ़ा सकते हैं।', en: 'Picking a role applies its usual permissions — you can adjust them under "Permissions".' },
  Roshni: { hi: 'रोशनी', en: 'Appearance' },
  'Round off': { hi: 'राउंड ऑफ', en: 'Round off' },
  Row: { hi: 'पंक्ति', en: 'Row' },
  'Rupees in words:': { hi: 'शब्दों में रकम:', en: 'Rupees in words:' },
  'Saaf karein': { hi: 'साफ करें', en: 'Clear' },
  'Saare items': { hi: 'सारे आइटम', en: 'All items' },
  'Saare items pe barabar bat jayega': { hi: 'सारे आइटम पर बराबर बंट जाएगा', en: 'Split equally across all items' },
  'Saari notifications dekhein': { hi: 'सारी सूचनाएं देखें', en: 'See all notifications' },
  Sab: { hi: 'सब', en: 'All' },
  'Sab categories': { hi: 'सब श्रेणियां', en: 'All categories' },
  'Sab chunein': { hi: 'सब चुनें', en: 'Select all' },
  'Sab items pe ek saath rate': { hi: 'सब आइटम पर एक साथ रेट', en: 'Set a rate on all items at once' },
  'Sab log': { hi: 'सब लोग', en: 'Everyone' },
  'Sab padh liya': { hi: 'सब पढ़ लिया', en: 'Mark all read' },
  'Sab pe ek saath': { hi: 'सब पर एक साथ', en: 'All at once' },
  'Sab retailers': { hi: 'सब रिटेलर', en: 'All retailers' },
  'Sab suppliers': { hi: 'सब सप्लायर', en: 'All suppliers' },
  'Sabse zyada bike': { hi: 'सबसे ज़्यादा बिके', en: 'Best sellers' },
  'Sabse zyada udhaar': { hi: 'सबसे ज़्यादा उधार', en: 'Highest dues' },
  Sale: { hi: 'सेल', en: 'Sale' },
  'Sale price': { hi: 'बिक्री रेट', en: 'Sale price' },
  'Save karein': { hi: 'सेव करें', en: 'Save' },
  'Scanner se search karne ke liye': { hi: 'स्कैनर से खोजने के लिए', en: 'For searching with a scanner' },
  Settings: { hi: 'सेटिंग', en: 'Settings' },
  Sheher: { hi: 'शहर', en: 'City' },
  'Shuruaat ka hisaab': { hi: 'शुरुआत का हिसाब', en: 'Opening balance' },
  'Sirf aapka apna — kisi aur ka yahan se nahi badalta': { hi: 'सिर्फ आपका अपना — किसी और का यहां से नहीं बदलता', en: 'Only yours — nobody else can be changed from here' },
  'Sirf akshar nahi — button aur khaane bhi utne hi bade honge, taaki ungli se dabane me aasani rahe.': { hi: 'सिर्फ अक्षर नहीं — बटन और खाने भी उतने ही बड़े होंगे, ताकि उंगली से दबाने में आसानी रहे।', en: 'Not just the text — buttons and fields grow too, so they are easier to tap.' },
  'Sirf apna kaam': { hi: 'सिर्फ अपना काम', en: 'Own work only' },
  'Sirf is number ke liye (marzi se)': { hi: 'सिर्फ इस नंबर के लिए (मर्ज़ी से)', en: 'For this number only (optional)' },
  'Sirf malik bana sakta hai': { hi: 'सिर्फ मालिक बना सकता है', en: 'Only the owner can create this' },
  'Sirf nayi': { hi: 'सिर्फ नई', en: 'Unread only' },
  'Sirf wahi retailer dikhenge jo inke naam hain ya jo inhone khud jode. Unke order, bill aur khata bhi apne aap isi hadd me aa jayenge.': { hi: 'सिर्फ वही रिटेलर दिखेंगे जो इनके नाम हैं या जो इन्होंने खुद जोड़े। उनके ऑर्डर, बिल और खाता भी अपने आप इसी हद में आ जाएंगे।', en: 'They will only see retailers assigned to them or added by them. Those orders, bills and ledgers are limited the same way automatically.' },
  State: { hi: 'राज्य', en: 'State' },
  'State chunein': { hi: 'राज्य चुनें', en: 'Choose state' },
  Stock: { hi: 'स्टॉक', en: 'Stock' },
  'Stock badlein': { hi: 'स्टॉक बदलें', en: 'Adjust stock' },
  'Stock ki keemat': { hi: 'स्टॉक की कीमत', en: 'Stock value' },
  'Stock pe asar': { hi: 'स्टॉक पर असर', en: 'Effect on stock' },
  'Stock utna hi wapas ghat jayega aur supplier ka khata bhi ulta ho jayega. Agar wo maal bik chuka hai to delete nahi hoga.': { hi: 'स्टॉक उतना ही वापस घट जाएगा और सप्लायर का खाता भी उल्टा हो जाएगा। अगर वो माल बिक चुका है तो डिलीट नहीं होगा।', en: 'Stock is reduced back by the same amount and the supplier ledger is reversed. If those goods are already sold it will not delete.' },
  Supplier: { hi: 'सप्लायर', en: 'Supplier' },
  'Supplier chunein': { hi: 'सप्लायर चुनें', en: 'Choose supplier' },
  'Supplier ka bill number': { hi: 'सप्लायर का बिल नंबर', en: 'Supplier bill number' },
  'Supplier ko phone kar dijiye': { hi: 'सप्लायर को फोन कर दीजिए', en: 'Give the supplier a call' },
  'Supplier se aaya maal — stock apne aap badhta hai': { hi: 'सप्लायर से आया माल — स्टॉक अपने आप बढ़ता है', en: 'Goods received from a supplier — stock increases automatically' },
  'Suppliers ko dena': { hi: 'सप्लायर को देना', en: 'Payable to suppliers' },
  Tareekh: { hi: 'तारीख', en: 'Date' },
  Tax: { hi: 'टैक्स', en: 'Tax' },
  'Tax invoice pe chhapega': { hi: 'टैक्स बिल पर छपेगा', en: 'Prints on the tax invoice' },
  Taxable: { hi: 'कर योग्य', en: 'Taxable' },
  'Taxable value': { hi: 'कर योग्य रकम', en: 'Taxable value' },
  'Tayyar hain': { hi: 'तैयार हैं', en: 'Ready' },
  'Terms & Conditions': { hi: 'शर्तें', en: 'Terms and Conditions' },
  'Theek hai': { hi: 'ठीक है', en: 'OK' },
  'Theek hai, samajh gaya': { hi: 'ठीक है, समझ गया', en: 'Got it' },
  'Top retailers': { hi: 'बड़े रिटेलर', en: 'Top retailers' },
  Total: { hi: 'कुल', en: 'Total' },
  'Udhaar baaki': { hi: 'उधार बाकी', en: 'Credit outstanding' },
  'Udhaar pe bill bana sakte hain': { hi: 'उधार पर बिल बना सकते हैं', en: 'Can bill on credit' },
  Unit: { hi: 'इकाई', en: 'Unit' },
  Update: { hi: 'अपडेट', en: 'Update' },
  'UPI pe naam': { hi: 'UPI पर नाम', en: 'Name on UPI' },
  'UPI se paisa lena': { hi: 'UPI से पैसा लेना', en: 'Accept money over UPI' },
  'Vyakti ka naam': { hi: 'व्यक्ति का नाम', en: 'Person name' },
  'Wajah (marzi)': { hi: 'वजह (मर्ज़ी)', en: 'Reason (optional)' },
  'Wapas aaya (kul)': { hi: 'वापस आया (कुल)', en: 'Returned in (total)' },
  'Wapas bheja (kul)': { hi: 'वापस भेजा (कुल)', en: 'Sent back (total)' },
  Warranty: { hi: 'वारंटी', en: 'Warranty' },
  'Warranty daal denge to retailer ko catalog aur bill — dono jagah dikhegi': { hi: 'वारंटी डाल देंगे तो रिटेलर को कैटलॉग और बिल — दोनों जगह दिखेगी', en: 'Fill in warranty and the retailer sees it both in the catalog and on the bill' },
  'Warranty ki shart': { hi: 'वारंटी की शर्त', en: 'Warranty terms' },
  'WhatsApp pe bhejein': { hi: 'WhatsApp पर भेजें', en: 'Send on WhatsApp' },
  'wholesale price': { hi: 'होलसेल रेट', en: 'wholesale price' },
  'Wholesale price': { hi: 'होलसेल रेट', en: 'Wholesale price' },
  'Wholesaler account': { hi: 'होलसेलर अकाउंट', en: 'Wholesaler account' },
  'Wholesaler account banayein': { hi: 'होलसेलर अकाउंट बनाएं', en: 'Create a wholesaler account' },
  'Ya khud likhein': { hi: 'या खुद लिखें', en: 'Or write your own' },
  'Yahi ek link apne saare retailers ko WhatsApp pe bhej dein': { hi: 'यही एक लिंक अपने सारे रिटेलर को WhatsApp पर भेज दें', en: 'Send this one link to all your retailers on WhatsApp' },
  'Ye daal denge to retailer apne phone se seedha aapko paisa bhej payega': { hi: 'ये डाल देंगे तो रिटेलर अपने फोन से सीधे आपको पैसा भेज पाएगा', en: 'Fill this and retailers can pay you straight from their phone' },
  'Ye data kahan rehta hai': { hi: 'ये डेटा कहां रहता है', en: 'Where this data lives' },
  'Ye file aapke computer me download hogi — kahin upload nahi hoti. Password kabhi is file me nahi jata. File ko Google Drive ya pendrive me rakh dijiye.': { hi: 'ये फाइल आपके कंप्यूटर में डाउनलोड होगी — कहीं अपलोड नहीं होती। पासवर्ड कभी इस फाइल में नहीं जाता। फाइल को Google Drive या पेनड्राइव में रख दीजिए।', en: 'This file downloads to your computer — it is not uploaded anywhere. Passwords never go into it. Keep the file on Google Drive or a pen drive.' },
  'Ye khatam hone wale hain': { hi: 'ये खत्म होने वाले हैं', en: 'These are about to run out' },
  'Ye link ab dobara nahi dikhegi.': { hi: 'ये लिंक अब दोबारा नहीं दिखेगी।', en: 'This link will not be shown again.' },
  'Ye link sirf dukaan ke malik ke paas rehta hai. Kisi naye retailer ko jodna ho to unse link mangwa lijiye.': { hi: 'ये लिंक सिर्फ दुकान के मालिक के पास रहता है। किसी नए रिटेलर को जोड़ना हो तो उनसे लिंक मंगवा लीजिए।', en: 'Only the shop owner holds this link. To add a new retailer, ask them for it.' },
  'Ye notification hatayein': { hi: 'ये सूचना हटाएं', en: 'Remove this notification' },
  'Ye page aapke liye nahi khula': { hi: 'ये पेज आपके लिए नहीं खुला', en: 'This page is not open to you' },
  'Ye sirf andaza hai — asli return CA hi bharega. Yahan se CSV nikaal kar de dijiye.': { hi: 'ये सिर्फ अंदाज़ा है — असली रिटर्न CA ही भरेगा। यहां से CSV निकाल कर दे दीजिए।', en: 'This is only an estimate — your CA files the actual return. Export the CSV here and hand it over.' },
  Cancelled: { hi: 'रद्द', en: 'Cancelled' },
  CANCELLED: { hi: 'रद्द', en: 'CANCELLED' },
  'CSV import': { hi: 'CSV इम्पोर्ट', en: 'CSV import' },
  'Sample CSV': { hi: 'सैंपल CSV', en: 'Sample CSV' },
  'HSN code': { hi: 'HSN कोड', en: 'HSN code' },
  'Zyada se zyada discount %': { hi: 'ज़्यादा से ज़्यादा छूट %', en: 'Maximum discount %' },
  Aa: { hi: 'अ', en: 'Aa' },

  /* ── config me likhe shabd: nav, tab, chip, table ke sar ── */
  Dashboard: { hi: 'डैशबोर्ड', en: 'Dashboard' },
  Home: { hi: 'होम', en: 'Home' },
  Catalog: { hi: 'कैटलॉग', en: 'Catalog' },
  Cart: { hi: 'कार्ट', en: 'Cart' },
  'My Orders': { hi: 'मेरे ऑर्डर', en: 'My Orders' },
  'Mere Bills': { hi: 'मेरे बिल', en: 'My Bills' },
  'My Khata': { hi: 'मेरा खाता', en: 'My Ledger' },
  Profile: { hi: 'प्रोफाइल', en: 'Profile' },
  Returns: { hi: 'रिटर्न', en: 'Returns' },
  Wapasi: { hi: 'वापसी', en: 'Return' },
  Staff: { hi: 'स्टाफ', en: 'Staff' },
  Party: { hi: 'पार्टी', en: 'Party' },
  Wholesaler: { hi: 'होलसेलर', en: 'Wholesaler' },
  Manager: { hi: 'मैनेजर', en: 'Manager' },
  Salesman: { hi: 'सेल्समैन', en: 'Salesman' },
  Munshi: { hi: 'मुंशी', en: 'Accountant' },

  /* ── roshni aur akshar ke chunav ── */
  Din: { hi: 'दिन', en: 'Day' },
  Raat: { hi: 'रात', en: 'Night' },
  'Phone jaisa': { hi: 'फोन जैसा', en: 'Match phone' },
  'Safed background': { hi: 'सफेद बैकग्राउंड', en: 'Light background' },
  'Aankh pe halka': { hi: 'आंख पर हल्का', en: 'Easy on the eyes' },
  'Phone ki setting maanein': { hi: 'फोन की सेटिंग मानें', en: 'Follow phone setting' },
  Chhota: { hi: 'छोटा', en: 'Small' },
  Normal: { hi: 'सामान्य', en: 'Normal' },
  Bada: { hi: 'बड़ा', en: 'Large' },
  'Sabse bada': { hi: 'सबसे बड़ा', en: 'Largest' },
  'Jaisa abhi hai': { hi: 'जैसा अभी है', en: 'As it is now' },
  'पूरी हिन्दी में': { hi: 'पूरी हिन्दी में', en: 'Full Hindi' },
  'In English': { hi: 'अंग्रेजी में', en: 'In English' },

  /* ── settings ke tab ── */
  App: { hi: 'ऐप', en: 'App' },
  Dukaan: { hi: 'दुकान', en: 'Shop' },
  'Invite link': { hi: 'इनवाइट लिंक', en: 'Invite link' },
  'Log aur login': { hi: 'लॉग और लॉगिन', en: 'Logs and logins' },
  Backup: { hi: 'बैकअप', en: 'Backup' },
  Account: { hi: 'अकाउंट', en: 'Account' },
  Detail: { hi: 'जानकारी', en: 'Details' },
  Status: { hi: 'हालत', en: 'Status' },
  Retailers: { hi: 'रिटेलर', en: 'Retailers' },
  Suppliers: { hi: 'सप्लायर', en: 'Suppliers' },
  'Retailers aur suppliers': { hi: 'रिटेलर और सप्लायर', en: 'Retailers and suppliers' },
  'Retailers se lena': { hi: 'रिटेलर से लेना', en: 'Receivable from retailers' },

  /* ── paisa aur hisaab ── */
  Cash: { hi: 'कैश', en: 'Cash' },
  Bank: { hi: 'बैंक', en: 'Bank' },
  Cheque: { hi: 'चेक', en: 'Cheque' },
  Udhaar: { hi: 'उधार', en: 'Credit' },
  Wholesale: { hi: 'होलसेल', en: 'Wholesale' },
  Aaya: { hi: 'आया', en: 'In' },
  Lagega: { hi: 'लगेगा', en: 'Applies' },
  'Baaki hai': { hi: 'बाकी है', en: 'Outstanding' },
  'Kuch diya': { hi: 'कुछ दिया', en: 'Part paid' },
  'Kuch mila': { hi: 'कुछ मिला', en: 'Part received' },
  'Kis bill ka': { hi: 'किस बिल का', en: 'Against which bill' },
  'Poora khata': { hi: 'पूरा खाता', en: 'Full ledger' },
  'Saare bill': { hi: 'सारे बिल', en: 'All bills' },
  Fayda: { hi: 'फायदा', en: 'Profit' },
  Hadd: { hi: 'हद', en: 'Limit' },
  Kaise: { hi: 'कैसे', en: 'How' },
  'Kaun hai': { hi: 'कौन है', en: 'Who' },
  Dono: { hi: 'दोनों', en: 'Both' },
  Clear: { hi: 'चुकता', en: 'Clear' },
  Confirm: { hi: 'कन्फर्म', en: 'Confirm' },
  Reject: { hi: 'रिजेक्ट', en: 'Reject' },
  Pending: { hi: 'बाकी', en: 'Pending' },
  Blocked: { hi: 'ब्लॉक', en: 'Blocked' },
  Chalu: { hi: 'चालू', en: 'Active' },
  Juda: { hi: 'जुड़ा', en: 'Joined' },
  Tayyar: { hi: 'तैयार', en: 'Ready' },
  'Approve karna hai': { hi: 'अप्रूव करना है', en: 'Needs approval' },
  'Pack karna hai': { hi: 'पैक करना है', en: 'To be packed' },
  'Pack shuru karein': { hi: 'पैक शुरू करें', en: 'Start packing' },
  'Tayyar mark karein': { hi: 'तैयार मार्क करें', en: 'Mark as ready' },
  'De diya mark karein': { hi: 'दे दिया मार्क करें', en: 'Mark as delivered' },
  'Nahi (paise ke saath)': { hi: 'नहीं (पैसे के साथ)', en: 'No (paid with order)' },
  'Nahi hai': { hi: 'नहीं है', en: 'Not set' },
  'Pada hua': { hi: 'पड़ा हुआ', en: 'Sitting idle' },
  'Kam bacha': { hi: 'कम बचा', en: 'Running low' },
  'Bina category wale': { hi: 'बिना श्रेणी वाले', en: 'Without category' },
  'Khaas rate hata do': { hi: 'खास रेट हटा दो', en: 'Remove special rate' },
  'Sirf khaas rate wale': { hi: 'सिर्फ खास रेट वाले', en: 'Only special-rate items' },
  'Mangwa lein': { hi: 'मंगवा लें', en: 'Reorder' },
  'Wapas aaya': { hi: 'वापस आया', en: 'Returned in' },
  'Wapas bheja': { hi: 'वापस भेजा', en: 'Sent back' },
  'Retailer ne wapas kiya': { hi: 'रिटेलर ने वापस किया', en: 'Returned by retailer' },
  'Supplier ko wapas bheja': { hi: 'सप्लायर को वापस भेजा', en: 'Sent back to supplier' },
  'Stock aaya': { hi: 'स्टॉक आया', en: 'Stock in' },
  'Stock gaya': { hi: 'स्टॉक गया', en: 'Stock out' },
  'Ginti karke set': { hi: 'गिनती करके सेट', en: 'Set by counting' },
  'Order update': { hi: 'ऑर्डर अपडेट', en: 'Order update' },
  'Yaad dilana': { hi: 'याद दिलाना', en: 'Reminder' },
  'Sale price': { hi: 'बिक्री रेट', en: 'Sale price' },

  /* ── chhaant-chhaant (sort) aur samay ── */
  'Naye pehle': { hi: 'नए पहले', en: 'Newest first' },
  'Mehnga pehle': { hi: 'महंगा पहले', en: 'Costliest first' },
  'Naam (A-Z)': { hi: 'नाम (A-Z)', en: 'Name (A-Z)' },
  'Naam (Z-A)': { hi: 'नाम (Z-A)', en: 'Name (Z-A)' },
  'Stock (kam pehle)': { hi: 'स्टॉक (कम पहले)', en: 'Stock (lowest first)' },
  'Stock (zyada pehle)': { hi: 'स्टॉक (ज़्यादा पहले)', en: 'Stock (highest first)' },
  'Din ke hisaab se': { hi: 'दिन के हिसाब से', en: 'By day' },
  'Item ke hisaab se': { hi: 'आइटम के हिसाब से', en: 'By item' },
  'Retailer ke hisaab se': { hi: 'रिटेलर के हिसाब से', en: 'By retailer' },
  'Supplier ke hisaab se': { hi: 'सप्लायर के हिसाब से', en: 'By supplier' },
  '1 mahina': { hi: '1 महीना', en: '1 month' },
  '3 mahine': { hi: '3 महीने', en: '3 months' },
  '6 mahine': { hi: '6 महीने', en: '6 months' },
  '1 saal': { hi: '1 साल', en: '1 year' },
  '1.5 saal': { hi: '1.5 साल', en: '1.5 years' },
  '2 saal': { hi: '2 साल', en: '2 years' },
  '3 saal': { hi: '3 साल', en: '3 years' },
  '5 saal': { hi: '5 साल', en: '5 years' },

  /* ── rate ke niyam ── */
  'Purchase price pe % jyada': { hi: 'खरीद रेट पर % ज़्यादा', en: 'Purchase price plus %' },
  'Sale price se % kam': { hi: 'बिक्री रेट से % कम', en: 'Sale price minus %' },
  'Wholesale price se % kam': { hi: 'होलसेल रेट से % कम', en: 'Wholesale price minus %' },
  'Poore rupee me': { hi: 'पूरे रुपए में', en: 'To whole rupees' },
  'Aadhe rupee me': { hi: 'आधे रुपए में', en: 'To half rupees' },
  '5 ke multiple me': { hi: '5 के गुणक में', en: 'To multiples of 5' },
  '10 ke multiple me': { hi: '10 के गुणक में', en: 'To multiples of 10' },
  Payment: { hi: 'पेमेंट', en: 'Payment' },

  /* ── Part 15 step 2: Home, Add Sale, Profile, bill bhejna ── */
  'Add Sale': { hi: 'नई सेल', en: 'Add Sale' },
  'Sab sale': { hi: 'सब सेल', en: 'All sales' },
  'Party wise': { hi: 'पार्टी के हिसाब से', en: 'By party' },
  baaki: { hi: 'बाकी', en: 'due' },
  hadd: { hi: 'हद', en: 'limit' },
  'sab milakar': { hi: 'सब मिलाकर', en: 'in total' },
  'Naam, number ya bill se dhundhein...': { hi: 'नाम, नंबर या बिल से ढूंढें...', en: 'Search by name, number or bill...' },
  'Is duration me koi sale nahi': { hi: 'इस अवधि में कोई सेल नहीं', en: 'No sales in this period' },
  'Is duration me kisi ne kuch nahi kharida': { hi: 'इस अवधि में किसी ने कुछ नहीं खरीदा', en: 'Nobody bought anything in this period' },
  'Upar se doosra samay chunein, ya neeche se nayi sale add karein.': { hi: 'ऊपर से दूसरा समय चुनें, या नीचे से नई सेल जोड़ें।', en: 'Pick another period above, or add a new sale below.' },
  'Upar se doosra samay chunein.': { hi: 'ऊपर से दूसरा समय चुनें।', en: 'Pick another period above.' },
  '{shown} dikha rahe hain, kul {total}': { hi: '{shown} दिखा रहे हैं, कुल {total}', en: 'Showing {shown} of {total}' },
  'Yahan sirf aapke apne retailer ka kaam dikh raha hai': { hi: 'यहां सिर्फ आपके अपने रिटेलर का काम दिख रहा है', en: 'You are only seeing work for your own retailers' },

  'Retailer ka phone number': { hi: 'रिटेलर का फोन नंबर', en: 'Retailer phone number' },
  '10 digit daalte hi purana graahak apne aap nikal aayega': { hi: '10 अंक डालते ही पुराना ग्राहक अपने आप निकल आएगा', en: 'Type 10 digits and an existing customer appears automatically' },
  'Dhundh raha hoon...': { hi: 'ढूंढ रहा हूं...', en: 'Searching...' },
  'Naya graahak hai — yahin bana lein': { hi: 'नया ग्राहक है — यहीं बना लें', en: 'New customer — create them right here' },
  'Bas naam chahiye. Address aur GST baad me Retailers page se bhar sakte hain.': { hi: 'बस नाम चाहिए। पता और GST बाद में रिटेलर पेज से भर सकते हैं।', en: 'Only the name is needed. Address and GST can be filled later from the Retailers page.' },
  'Jodkar aage badhein': { hi: 'जोड़कर आगे बढ़ें', en: 'Add and continue' },
  'Number se dhundhein': { hi: 'नंबर से ढूंढें', en: 'Search by number' },
  'Number yaad nahi? Naam se dhundhein': { hi: 'नंबर याद नहीं? नाम से ढूंढें', en: 'Forgot the number? Search by name' },
  'Naam ya dukaan se dhundhein': { hi: 'नाम या दुकान से ढूंढें', en: 'Search by name or shop' },
  'Ye number kisi aur ke naam hai. Malik se kahiye ki ye retailer aapke naam kar dein.': { hi: 'ये नंबर किसी और के नाम है। मालिक से कहिए कि ये रिटेलर आपके नाम कर दें।', en: 'This number belongs to someone else. Ask the owner to assign this retailer to you.' },
  'Purana udhaar': { hi: 'पुराना उधार', en: 'Existing credit' },
  Badlein: { hi: 'बदलें', en: 'Change' },
  'Upload karein': { hi: 'अपलोड करें', en: 'Upload' },
  'Bill pe yahi chhapega': { hi: 'बिल पर यही छपेगा', en: 'This is what prints on the bill' },

  'Paisa kahan bhejein': { hi: 'पैसा कहां भेजें', en: 'Where to send the money' },
  'Bhejni hai': { hi: 'भेजनी है', en: 'To pay' },
  'UPI QR': { hi: 'UPI QR', en: 'UPI QR' },
  'Kisi bhi UPI app se scan karein': { hi: 'किसी भी UPI ऐप से स्कैन करें', en: 'Scan with any UPI app' },
  'Bank wale khate ka QR nahi banta — ye number apne bank app me daalein': { hi: 'बैंक वाले खाते का QR नहीं बनता — ये नंबर अपने बैंक ऐप में डालें', en: 'A bank account cannot make a QR — enter these details in your bank app' },
  'UPI — QR wala rasta': { hi: 'UPI — QR वाला रास्ता', en: 'UPI — the QR route' },
  'Bill pe QR isi se banta hai. Retailer scan karke seedha paisa bhej deta hai.': { hi: 'बिल पर QR इसी से बनता है। रिटेलर स्कैन करके सीधे पैसा भेज देता है।', en: 'The QR on the bill is made from this. The retailer scans and pays directly.' },
  'Har bill pe baaki rakam ka QR apne aap ban jayega — retailer ko rakam bharni bhi nahi padegi.': { hi: 'हर बिल पर बाकी रकम का QR अपने आप बन जाएगा — रिटेलर को रकम भरनी भी नहीं पड़ेगी।', en: 'Every bill gets a QR for the outstanding amount automatically — the retailer does not even type it.' },
  'Bank ka khata — likhne wala rasta': { hi: 'बैंक का खाता — लिखने वाला रास्ता', en: 'Bank account — the written route' },
  'Ye bill pe likha jayega, taaki NEFT/IMPS karne wale seedha daal sakein.': { hi: 'ये बिल पर लिखा जाएगा, ताकि NEFT/IMPS करने वाले सीधे डाल सकें।', en: 'This prints on the bill so anyone paying by NEFT/IMPS can enter it directly.' },
  'Bank ka naam': { hi: 'बैंक का नाम', en: 'Bank name' },
  'Khate pe naam': { hi: 'खाते पर नाम', en: 'Account holder name' },
  'Account number': { hi: 'खाता नंबर', en: 'Account number' },
  IFSC: { hi: 'IFSC', en: 'IFSC' },
  'Account number aur IFSC se QR nahi ban sakta — UPI ka QR sirf UPI ID (naam@bank) se banta hai. Isliye account wali detail bill pe likhi jati hai, aur QR upar wali UPI ID se banta hai.': { hi: 'खाता नंबर और IFSC से QR नहीं बन सकता — UPI का QR सिर्फ UPI ID (नाम@bank) से बनता है। इसलिए खाते की जानकारी बिल पर लिखी जाती है, और QR ऊपर वाली UPI ID से बनता है।', en: 'An account number and IFSC cannot produce a QR — a UPI QR is only made from a UPI ID (name@bank). So account details are printed on the bill, and the QR comes from the UPI ID above.' },
  'Dono me se jo bhara hoga wahi bill pe aayega. Dono bhar denge to QR bhi rahega aur account bhi — retailer jo chahe use kar lega.': { hi: 'दोनों में से जो भरा होगा वही बिल पर आएगा। दोनों भर देंगे तो QR भी रहेगा और खाता भी — रिटेलर जो चाहे इस्तेमाल कर लेगा।', en: 'Whichever you fill is what appears on the bill. Fill both and the bill carries both — the retailer picks whichever suits them.' },

  'Dukaan ki pehchan, paisa lene ka tarika aur apna login': { hi: 'दुकान की पहचान, पैसा लेने का तरीका और अपना लॉगिन', en: 'Shop identity, how you get paid, and your own login' },
  'Aapka apna login': { hi: 'आपका अपना लॉगिन', en: 'Your own login' },
  'Dukaan ki detail sirf malik badal sakta hai': { hi: 'दुकान की जानकारी सिर्फ मालिक बदल सकता है', en: 'Only the owner can change shop details' },
  'Bill aur stock': { hi: 'बिल और स्टॉक', en: 'Bill and stock' },
  'Ye shart har naye bill ke neeche chhapegi. Purane bill jaise the waise hi rahenge.': { hi: 'ये शर्त हर नए बिल के नीचे छपेगी। पुराने बिल जैसे थे वैसे ही रहेंगे।', en: 'These terms print on every new bill. Old bills stay exactly as they were.' },
  "Off rakha to bill 'Bill of Supply' banega — koi tax column nahi. On karne par 'Tax Invoice' banega.": { hi: "बंद रखा तो बिल 'Bill of Supply' बनेगा — कोई टैक्स कॉलम नहीं। चालू करने पर 'Tax Invoice' बनेगा।", en: "Off means bills are a 'Bill of Supply' — no tax columns. On makes them a 'Tax Invoice'." },
  "GPay/PhonePe app me 'UPI ID' ke naam se milti hai": { hi: "GPay/PhonePe ऐप में 'UPI ID' के नाम से मिलती है", en: "Found as 'UPI ID' inside the GPay/PhonePe app" },
  'App, invite link, staff aur backup': { hi: 'ऐप, इनवाइट लिंक, स्टाफ और बैकअप', en: 'App, invite link, staff and backup' },
  'Ab do kaam: Profile me dukaan ka address, GST aur UPI bhar lein (bill pe yahi chhapega), aur "Invite link" tab se apna link WhatsApp pe bhej dein.': { hi: 'अब दो काम: Profile में दुकान का पता, GST और UPI भर लें (बिल पर यही छपेगा), और "Invite link" टैब से अपना लिंक WhatsApp पर भेज दें।', en: 'Two things now: fill your shop address, GST and UPI in Profile (that is what prints on bills), and send your link from the "Invite link" tab on WhatsApp.' },
  'Profile bharein': { hi: 'प्रोफाइल भरें', en: 'Fill profile' },
  '"WhatsApp" dabate hi bill ki PDF ban kar share ka parda khulta hai — wahan se seedha retailer ko bhej dein. "Print" se kagaz ya PDF, dono ho jate hain.': { hi: '"WhatsApp" दबाते ही बिल की PDF बन कर शेयर का पर्दा खुलता है — वहां से सीधे रिटेलर को भेज दें। "Print" से कागज या PDF, दोनों हो जाते हैं।', en: 'Pressing "WhatsApp" builds a PDF of the bill and opens the share sheet — send it straight to the retailer. "Print" gives you paper or a PDF.' },

  /* ── Part 15 step 3: kharch aur fayda-nuksan ── */
  Kharch: { hi: 'खर्च', en: 'Expenses' },
  'Kharch likhein': { hi: 'खर्च लिखें', en: 'Add expense' },
  'Kharch badlein': { hi: 'खर्च बदलें', en: 'Edit expense' },
  'Pehla kharch likhein': { hi: 'पहला खर्च लिखें', en: 'Add your first expense' },
  'Likh lein': { hi: 'लिख लें', en: 'Save it' },
  'Kis cheez ka': { hi: 'किस चीज़ का', en: 'What for' },
  'Kaise diya': { hi: 'कैसे दिया', en: 'How paid' },
  'Kisko diya (marzi se)': { hi: 'किसको दिया (मर्ज़ी से)', en: 'Paid to (optional)' },
  'Naya naam': { hi: 'नया नाम', en: 'New name' },
  'Jaise: generator ka diesel': { hi: 'जैसे: जनरेटर का डीज़ल', en: 'e.g. generator diesel' },
  'Ek baar likh dein — agli baar ye bhi chip banke aa jayega': { hi: 'एक बार लिख दें — अगली बार ये भी चिप बनकर आ जाएगा', en: 'Type it once — next time it appears as a chip' },
  'Ramu / Bharat Petrol Pump': { hi: 'रामू / भारत पेट्रोल पंप', en: 'Ramu / Bharat Petrol Pump' },
  'Gaadi UP78 AB 1234 me daala': { hi: 'गाड़ी UP78 AB 1234 में डाला', en: 'Filled in vehicle UP78 AB 1234' },
  'Jo paisa dukaan se bahar gaya — chai se lekar kiraya tak': { hi: 'जो पैसा दुकान से बाहर गया — चाय से लेकर किराया तक', en: 'Money that left the shop — from tea to rent' },
  'Chai, petrol, tankhwah, kiraya — jo bhi paisa maal ke alawa bahar gaya': { hi: 'चाय, पेट्रोल, तनख्वाह, किराया — जो भी पैसा माल के अलावा बाहर गया', en: 'Tea, petrol, salary, rent — money spent on anything other than goods' },
  'Kisko diya, note ya number se dhundhein...': { hi: 'किसको दिया, नोट या नंबर से ढूंढें...', en: 'Search by payee, note or number...' },
  'Is duration me koi kharch nahi': { hi: 'इस अवधि में कोई खर्च नहीं', en: 'No expenses in this period' },
  'Chai, petrol, mazdoori — jo bhi paisa gaya, yahan likh dein. Mahine ke aakhir me asli fayda tabhi dikhega.': { hi: 'चाय, पेट्रोल, मज़दूरी — जो भी पैसा गया, यहां लिख दें। महीने के आखिर में असली फायदा तभी दिखेगा।', en: 'Tea, petrol, wages — write down whatever went out. Only then does month-end profit mean anything.' },
  'Ye kharch hata dein?': { hi: 'ये खर्च हटा दें?', en: 'Remove this expense?' },
  'ye wapas nahi aayega. Register me likha rahega ki kisne hataya.': { hi: 'ये वापस नहीं आएगा। रजिस्टर में लिखा रहेगा कि किसने हटाया।', en: 'this cannot be undone. The log will record who removed it.' },
  'Ye kharch "Fayda-Nuksan" report me apne aap ghat jate hain.': { hi: 'ये खर्च "फायदा-नुकसान" रिपोर्ट में अपने आप घट जाते हैं।', en: 'These expenses are deducted automatically in the Profit & Loss report.' },
  'Maal khareedna kharch nahi hai — wo "Purchase" me jata hai. Yahan sirf wo paisa likhein jo maal ke alawa bahar gaya.': { hi: 'माल खरीदना खर्च नहीं है — वो "Purchase" में जाता है। यहां सिर्फ वो पैसा लिखें जो माल के अलावा बाहर गया।', en: 'Buying goods is not an expense — that goes under "Purchase". Record only money spent on things other than stock.' },
  entry: { hi: 'एंट्री', en: 'entries' },
  'is mahine': { hi: 'इस महीने', en: 'this month' },
  bill: { hi: 'बिल', en: 'bills' },
  se: { hi: 'से', en: 'to' },

  'Fayda-Nuksan': { hi: 'फायदा-नुकसान', en: 'Profit & Loss' },
  'Poora hisaab': { hi: 'पूरा हिसाब', en: 'Full statement' },
  'Sale (bina GST)': { hi: 'सेल (बिना GST)', en: 'Sales (excl. GST)' },
  'Asli sale': { hi: 'असली सेल', en: 'Net sales' },
  'Maal ki lagat': { hi: 'माल की लागत', en: 'Cost of goods sold' },
  'jitna maal bika, wo aapko kitne ka pada': { hi: 'जितना माल बिका, वो आपको कितने का पड़ा', en: 'what the goods you sold cost you' },
  'Maal ka fayda': { hi: 'माल का फायदा', en: 'Gross profit' },
  'Dukaan ka kharch': { hi: 'दुकान का खर्च', en: 'Shop expenses' },
  'Asli fayda': { hi: 'असली फायदा', en: 'Net profit' },
  Nuksaan: { hi: 'नुकसान', en: 'Loss' },
  'Maal pe fayda': { hi: 'माल पर फायदा', en: 'Gross margin' },
  'Sab kharch ke baad': { hi: 'सब खर्च के बाद', en: 'Net margin' },
  'Is duration me kuch nahi hua': { hi: 'इस अवधि में कुछ नहीं हुआ', en: 'Nothing happened in this period' },
  'Date range badal kar dekhein.': { hi: 'तारीख की सीमा बदल कर देखें।', en: 'Try changing the date range.' },
  'GST kamaai nahi hai.': { hi: 'GST कमाई नहीं है।', en: 'GST is not income.' },
  'Graahak se liya hua tax sarkar ka hai, aapka nahi — isliye upar wali sale me wo nahi juda.': { hi: 'ग्राहक से लिया हुआ टैक्स सरकार का है, आपका नहीं — इसलिए ऊपर वाली सेल में वो नहीं जुड़ा।', en: 'Tax collected from customers belongs to the government, not you — so it is not included in the sales figure above.' },
  'Is duration me aapne': { hi: 'इस अवधि में आपने', en: 'In this period you collected' },
  'GST ikattha kiya hai.': { hi: 'GST इकट्ठा किया है।', en: 'in GST.' },
  'Maal khareedna kharch nahi hai.': { hi: 'माल खरीदना खर्च नहीं है।', en: 'Buying goods is not an expense.' },
  'Aaj ₹1 lakh ka maal khareeda aur kuch nahi becha — nuksaan nahi hua, paisa maal me badal gaya. Lagat tabhi ginti hai jab wo maal bikta hai.': { hi: 'आज ₹1 लाख का माल खरीदा और कुछ नहीं बेचा — नुकसान नहीं हुआ, पैसा माल में बदल गया। लागत तभी गिनती है जब वो माल बिकता है।', en: 'Buy ₹1 lakh of stock today and sell nothing — that is not a loss, the money simply became stock. It becomes cost only when those goods sell.' },
  'Ye nakad ka hisaab nahi hai.': { hi: 'ये नकद का हिसाब नहीं है।', en: 'This is not a cash statement.' },
  'Udhaar becha hua maal bhi sale me hai, chahe paisa abhi na aaya ho. "Kitna paisa aaya" ke liye Khata dekhein.': { hi: 'उधार बेचा हुआ माल भी सेल में है, चाहे पैसा अभी न आया हो। "कितना पैसा आया" के लिए खाता देखें।', en: 'Goods sold on credit count as sales even if the money has not arrived. For "how much cash came in", see the Ledger.' },

  /* kharch ki shreniyan */
  'Chai-paani': { hi: 'चाय-पानी', en: 'Tea and snacks' },
  'Petrol / diesel': { hi: 'पेट्रोल / डीज़ल', en: 'Petrol / diesel' },
  'Transport / bhada': { hi: 'ट्रांसपोर्ट / भाड़ा', en: 'Transport / freight' },
  Tankhwah: { hi: 'तनख्वाह', en: 'Salary' },
  Kiraya: { hi: 'किराया', en: 'Rent' },
  'Bijli / paani': { hi: 'बिजली / पानी', en: 'Electricity / water' },
  'Phone / internet': { hi: 'फोन / इंटरनेट', en: 'Phone / internet' },
  Packing: { hi: 'पैकिंग', en: 'Packing' },
  Marammat: { hi: 'मरम्मत', en: 'Repairs' },
  'Tax / fees': { hi: 'टैक्स / फीस', en: 'Tax / fees' },
  'Aur kuch': { hi: 'और कुछ', en: 'Something else' },
  'Pichhla mahina': { hi: 'पिछला महीना', en: 'Last month' },
  'Is saal': { hi: 'इस साल', en: 'This year' },

  /* ---- Part 15, step 4: Dashboard, Sale aur Payment page ---- */

  // dashboard ke chhote tile
  'Aaj ka kharch': { hi: 'आज का खर्च', en: "Today's expenses" },
  'Mahine me': { hi: 'महीने में', en: 'This month' },
  'Is mahine sale': { hi: 'इस महीने सेल', en: 'Sales this month' },
  'Chai, petrol, kiraya — jo bhi aaj gaya': {
    hi: 'चाय, पेट्रोल, किराया — जो भी आज गया',
    en: 'Tea, fuel, rent — whatever went out today',
  },
  retailer: { hi: 'रिटेलर', en: 'retailer' },
  item: { hi: 'आइटम', en: 'item' },
  bacha: { hi: 'बचा', en: 'left' },
  'Abhi koi sale nahi': { hi: 'अभी कोई सेल नहीं', en: 'No sales yet' },
  'Kuch nahi hua abhi tak': { hi: 'कुछ नहीं हुआ अभी तक', en: 'Nothing has happened yet' },

  // Sale page
  Kal: { hi: 'कल', en: 'Yesterday' },
  'Kis din kitna bika aur kiska paisa baaki hai': {
    hi: 'किस दिन कितना बिका और किसका पैसा बाकी है',
    en: 'What sold on which day, and whose payment is pending',
  },
  '7 din': { hi: '7 दिन', en: '7 days' },
  'Date chunein': { hi: 'तारीख चुनें', en: 'Pick dates' },
  'Kis din se': { hi: 'किस दिन से', en: 'From' },
  'Kis din tak': { hi: 'किस दिन तक', en: 'To' },
  'Is duration me koi bill nahi': { hi: 'इस अवधि में कोई बिल नहीं', en: 'No bills in this period' },
  'Upar wale chip se duration badal kar dekhein — ya yahin se naya bill banayein.': {
    hi: 'ऊपर वाले चिप से अवधि बदल कर देखें — या यहीं से नया बिल बनाएँ।',
    en: 'Change the period using the chips above — or make a new bill right here.',
  },

  // Payment page — "kitna purana"
  'aaj ka': { hi: 'आज का', en: 'from today' },
  'kal ka': { hi: 'कल का', en: 'from yesterday' },
  'din purana': { hi: 'दिन पुराना', en: 'days old' },
  '1 mahina purana': { hi: '1 महीना पुराना', en: '1 month old' },
  'mahine purana': { hi: 'महीने पुराना', en: 'months old' },

  // Payment page — baaki sab
  'Kisse lena hai, aur ab tak kya kya aaya': {
    hi: 'किससे लेना है, और अब तक क्या क्या आया',
    en: 'Who owes you, and everything received so far',
  },
  'Kul lena hai': { hi: 'कुल लेना है', en: 'Total receivable' },
  'payment confirm karna hai': { hi: 'पेमेंट कन्फर्म करनी है', en: 'payments to confirm' },
  'Inke app me alert chala jayega ki itna paisa baaki hai. WhatsApp bhejna ho to uske bagal wala button dabaein.': {
    hi: 'इनके ऐप में अलर्ट चला जाएगा कि इतना पैसा बाकी है। WhatsApp भेजना हो तो उसके बगल वाला बटन दबाएँ।',
    en: 'They will get an alert in their app about the pending amount. To send a WhatsApp message, use the button next to it.',
  },
  'Naam ya number...': { hi: 'नाम या नंबर...', en: 'Name or number...' },
  'Sabse zyada': { hi: 'सबसे ज़्यादा', en: 'Largest first' },
  'Purana pehle': { hi: 'पुराना पहले', en: 'Oldest first' },
  'Naam se': { hi: 'नाम से', en: 'By name' },
  'retailer se lena hai': { hi: 'रिटेलर से लेना है', en: 'retailers owe you' },
  'Is naam se koi nahi mila': { hi: 'इस नाम से कोई नहीं मिला', en: 'No one found by that name' },
  'Kisi ka udhaar baaki nahi': { hi: 'किसी का उधार बाकी नहीं', en: 'No pending dues' },
  'Naam ya number dobara dekh lein.': { hi: 'नाम या नंबर दोबारा देख लें।', en: 'Check the name or number again.' },
  'Sabka hisaab saaf hai — badhiya baat hai.': {
    hi: 'सबका हिसाब साफ है — बढ़िया बात है।',
    en: 'Everyone is settled up — that is a good thing.',
  },
  'number nahi hai': { hi: 'नंबर नहीं है', en: 'no number saved' },
  'bill khula': { hi: 'बिल खुला', en: 'bill open' },
  'hadd paar': { hi: 'हद पार', en: 'over limit' },
  'Phone karein': { hi: 'फोन करें', en: 'Call' },
  'WhatsApp pe yaad dilayein': { hi: 'WhatsApp पर याद दिलाएँ', en: 'Remind on WhatsApp' },
  'App me yaad dilayein': { hi: 'ऐप में याद दिलाएँ', en: 'Remind in the app' },
  'Paisa aaya': { hi: 'पैसा आया', en: 'Money received' },

  'Dena hai': { hi: 'देना है', en: 'You owe' },
  'Supplier ko': { hi: 'सप्लायर को', en: 'To suppliers' },

  // Pagination ki neeche wali line — pehle `t()` me lipti hi nahi thi
  'Kul {n} item': { hi: 'कुल {n} आइटम', en: '{n} in total' },

  /* ---- Part 15, step 5: Menu page, Staff page aur Purchase ---- */

  // Menu page
  jagah: { hi: 'जगह', en: 'places' },
  'Menu me dhundhein': { hi: 'मेन्यू में ढूँढें', en: 'Search the menu' },
  'Kya kholna hai? Jaise "kharch" ya "udhaar"': {
    hi: 'क्या खोलना है? जैसे "खर्च" या "उधार"',
    en: 'What do you want to open? Try "expense" or "credit"',
  },
  'Khoj hatayein': { hi: 'खोज हटाएँ', en: 'Clear search' },
  'Kuch nahi mila': { hi: 'कुछ नहीं मिला', en: 'Nothing found' },
  'Doosre shabd se dekhein — jaise "bill", "paisa" ya "maal".': {
    hi: 'दूसरे शब्द से देखें — जैसे "बिल", "पैसा" या "माल"।',
    en: 'Try another word — like "bill", "money" or "stock".',
  },
  'Logout karein?': { hi: 'लॉगआउट करें?', en: 'Log out?' },
  'Dobara login karne ke liye phone number aur password lagega.': {
    hi: 'दोबारा लॉगिन करने के लिए फोन नंबर और पासवर्ड लगेगा।',
    en: 'You will need your phone number and password to log in again.',
  },

  // Menu me har naam ka ek line ka matlab
  'Aaj ka kaam — bill banaein, chhapein, bhejein': {
    hi: 'आज का काम — बिल बनाएँ, छापें, भेजें',
    en: "Today's work — make bills, print them, send them",
  },
  'Ek nazar me poori dukaan — sale, kharch aur graph': {
    hi: 'एक नज़र में पूरी दुकान — सेल, खर्च और ग्राफ',
    en: 'The whole shop at a glance — sales, expenses and charts',
  },
  'Retailer ne app se jo maal manga hai': {
    hi: 'रिटेलर ने ऐप से जो माल मँगाया है',
    en: 'What retailers have ordered through the app',
  },
  'Maal ki list, rate aur stock': { hi: 'माल की लिस्ट, रेट और स्टॉक', en: 'Item list, rates and stock' },
  'Jinko aap maal bechte hain': { hi: 'जिनको आप माल बेचते हैं', en: 'The people you sell to' },
  'Jinse aap maal khareedte hain': { hi: 'जिनसे आप माल खरीदते हैं', en: 'The people you buy from' },
  'Maal andar aaya — kis din kitna, aur kisko dena hai': {
    hi: 'माल अंदर आया — किस दिन कितना, और किसको देना है',
    en: 'Stock coming in — how much on which day, and who you owe',
  },
  'Maal wapas aaya ya wapas bheja': {
    hi: 'माल वापस आया या वापस भेजा',
    en: 'Goods returned to you or sent back',
  },
  'Har party ka poora lena-dena, ek ek entry': {
    hi: 'हर पार्टी का पूरा लेन-देन, एक एक एंट्री',
    en: 'Every single transaction for each party',
  },
  'Kisse udhaar lena hai, aur paisa aane-jaane ka record': {
    hi: 'किससे उधार लेना है, और पैसा आने-जाने का रिकॉर्ड',
    en: 'Who owes you, and the record of money in and out',
  },
  'Chai, petrol, kiraya, tankhwah — dukaan ka kharcha': {
    hi: 'चाय, पेट्रोल, किराया, तनख्वाह — दुकान का खर्चा',
    en: 'Tea, fuel, rent, salaries — the shop expenses',
  },
  'Fayda-nuksan, GST, stock aur baaki hisaab': {
    hi: 'फायदा-नुकसान, GST, स्टॉक और बाकी हिसाब',
    en: 'Profit and loss, GST, stock and other reports',
  },
  'Log, unki ijazat, hadd — aur kisne kya kiya': {
    hi: 'लोग, उनकी इजाज़त, हद — और किसने क्या किया',
    en: 'People, their permissions, limits — and who did what',
  },
  'Dukaan ka naam, UPI, bank aur apna account': {
    hi: 'दुकान का नाम, UPI, बैंक और अपना अकाउंट',
    en: 'Shop name, UPI, bank and your account',
  },
  'Bhasha, roshni, akshar ka size aur backup': {
    hi: 'भाषा, रोशनी, अक्षर का साइज़ और बैकअप',
    en: 'Language, theme, text size and backup',
  },
  'Aapka hisaab ek nazar me': { hi: 'आपका हिसाब एक नज़र में', en: 'Your account at a glance' },
  'Poora maal aur uske rate': { hi: 'पूरा माल और उसके रेट', en: 'All items and their rates' },
  'Jo maal aapne chuna hai': { hi: 'जो माल आपने चुना है', en: 'The items you have picked' },
  'Aapke bheje hue order': { hi: 'आपके भेजे हुए ऑर्डर', en: 'Orders you have placed' },
  'Aapke saare bill': { hi: 'आपके सारे बिल', en: 'All your bills' },
  'Kitna baaki hai': { hi: 'कितना बाकी है', en: 'How much is pending' },
  'Naye alert': { hi: 'नए अलर्ट', en: 'New alerts' },
  'Aapka account': { hi: 'आपका अकाउंट', en: 'Your account' },

  // Staff page
  'Kaam ka record': { hi: 'काम का रिकॉर्ड', en: 'Activity log' },
  'Aapka kiya hua kaam': { hi: 'आपका किया हुआ काम', en: 'Work you have done' },
  'Kaun kaun kaam karta hai, kiske paas kya chaabi hai, aur kisne kya kiya': {
    hi: 'कौन कौन काम करता है, किसके पास क्या चाबी है, और किसने क्या किया',
    en: 'Who works here, who has which keys, and who did what',
  },
  'App, invite link aur backup': { hi: 'ऐप, इनवाइट लिंक और बैकअप', en: 'App, invite link and backup' },

  // Purchase page
  'Maal aaya': { hi: 'माल आया', en: 'Stock in' },
  purchase: { hi: 'खरीद', en: 'purchase' },
  'Is duration me koi purchase nahi': { hi: 'इस अवधि में कोई खरीद नहीं', en: 'No purchases in this period' },
  'Upar wale chip se duration badal kar dekhein.': {
    hi: 'ऊपर वाले चिप से अवधि बदल कर देखें।',
    en: 'Change the period using the chips above.',
  },
  'Supplier se maal aaye to yahan entry karein — stock apne aap badh jayega aur unka khata bhi bante jayega.': {
    hi: 'सप्लायर से माल आए तो यहाँ एंट्री करें — स्टॉक अपने आप बढ़ जाएगा और उनका खाता भी बनता जाएगा।',
    en: 'Enter stock as it arrives — inventory goes up automatically and their ledger builds itself.',
  },
  'supplier ko dena hai': { hi: 'सप्लायर को देना है', en: 'suppliers to pay' },
  'Kisi supplier ka paisa baaki nahi': { hi: 'किसी सप्लायर का पैसा बाकी नहीं', en: 'You owe no supplier' },
  'purchase khuli': { hi: 'खरीद खुली', en: 'purchase open' },
  'WhatsApp pe likhein': { hi: 'WhatsApp पर लिखें', en: 'Message on WhatsApp' },
  'Paisa diya': { hi: 'पैसा दिया', en: 'Money paid' },
};

export default DICT;

/**
 * Jinka anuvaad JAAN BOOJH KAR nahi kiya.
 *
 * Naam, misaal ka data, brand aur sarkari short-form. Inhe yahan likh dena
 * zaroori hai — warna `npm run check` hamesha "itne shabd bache hain" bolta
 * rehta, aur kuch dinon me log us ginti ko dekhna hi chhod dete. Ginti tabhi
 * kaam ki hai jab wo ZERO ho sakti ho.
 */
export const NO_TRANSLATE = new Set([
  // sarkari / taknik ke short-form — kagaz pe bhi English me hi chhapte hain
  'GSTIN', 'GST %', 'CGST + SGST', 'WhatsApp',
  // app ka apna naam
  'Rakh Rakhav',
  // form me dikhne wali misaalein (placeholder)
  'Ramesh Auto Parts', 'Ramesh Kumar', 'Suresh Auto Store', 'Suresh Kumar',
  'Ramu — naya salesman', 'ramesh@okhdfcbank', '09AAACH7409R1ZZ', 'ST/2026/119',
  'HDFC Bank', 'HDFC0001234',
  'Bearings', 'Bearing 6203', 'BRG-6203', '6203-2RS', 'A-3', 'SKF, Bosch, Rolon...',
]);
